--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_4_7 = {
	{t=1,starts={x=1333.00,y=405.00},sct={x=1020.00,y=286.00},dct={x=817.00,y=-143.00},ends={x=634.00,y=15.00},duration= 7, section=-1},
	{t=1,starts={x=634.00,y=15.00},sct={x=-125.00,y=636.00},dct={x=444.26,y=770.83},ends={x=461.00,y=751.00},duration= 7, section=-1},
}
return fishpath_4_7
