--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_1_8 = {
	{t=1,starts={x=-23.00,y=271.00},sct={x=131.76,y=599.81},dct={x=294.00,y=61.00},ends={x=571.00,y=0.00},duration= 7, section=-1},
	{t=1,starts={x=571.00,y=0.00},sct={x=989.79,y=-81.57},dct={x=805.18,y=639.70},ends={x=1331.00,y=368.00},duration= 7, section=-1},
}
return fishpath_1_8
