--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_11_5 = {
	{t=1,starts={x=355.00,y=-62.00},sct={x=321.00,y=427.00},dct={x=-282.02,y=665.86},ends={x=1289.00,y=670.00},duration= 7, section=-1},
}
return fishpath_11_5
