--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_24_4 = {
	{t=1,starts={x=1323.00,y=618.00},sct={x=1429.31,y=540.29},dct={x=351.55,y=216.71},ends={x=198.00,y=-73.00},duration= 7, section=-1},
}
return fishpath_24_4
