--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_14_4 = {
	{t=1,starts={x=529.00,y=-53.00},sct={x=308.00,y=4.00},dct={x=159.29,y=180.52},ends={x=178.00,y=366.00},duration= 7, section=-1},
	{t=1,starts={x=178.00,y=366.00},sct={x=252.00,y=768.00},dct={x=919.00,y=511.00},ends={x=957.00,y=742.00},duration= 7, section=-1},
}
return fishpath_14_4
