--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_12_9 = {
	{t=1,starts={x=-40.00,y=155.00},sct={x=-28.93,y=171.42},dct={x=1401.41,y=1126.06},ends={x=882.00,y=279.00},duration= 7, section=-1},
	{t=1,starts={x=882.00,y=279.00},sct={x=541.25,y=-191.60},dct={x=330.56,y=606.10},ends={x=442.00,y=760.00},duration= 7, section=-1},
}
return fishpath_12_9
