--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_25_8 = {
	{t=1,starts={x=1314.00,y=500.00},sct={x=1238.85,y=554.33},dct={x=516.07,y=86.02},ends={x=736.00,y=-73.00},duration= 7, section=-1},
}
return fishpath_25_8
