--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_11_2 = {
	{t=1,starts={x=293.00,y=-65.00},sct={x=219.65,y=-56.13},dct={x=506.14,y=371.83},ends={x=918.00,y=322.00},duration= 7, section=-1},
	{t=1,starts={x=918.00,y=322.00},sct={x=1176.00,y=293.00},dct={x=1255.98,y=692.48},ends={x=1050.00,y=754.00},duration= 7, section=-1},
}
return fishpath_11_2
