--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_6_6 = {
	{t=1,starts={x=-22.00,y=82.00},sct={x=83.11,y=51.06},dct={x=1273.00,y=198.00},ends={x=535.00,y=508.00},duration= 7, section=-1},
	{t=1,starts={x=535.00,y=508.00},sct={x=-106.00,y=774.00},dct={x=1131.00,y=748.00},ends={x=1309.00,y=501.00},duration= 7, section=-1},
}
return fishpath_6_6
