--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_2_7 = {
	{t=1,starts={x=628.00,y=754.00},sct={x=919.00,y=476.00},dct={x=495.00,y=519.00},ends={x=155.00,y=343.00},duration= 7, section=-1},
	{t=1,starts={x=155.00,y=343.00},sct={x=-342.07,y=89.59},dct={x=688.00,y=133.00},ends={x=980.00,y=-58.00},duration= 7, section=-1},
}
return fishpath_2_7
