--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_20_6 = {
	{t=1,starts={x=1304.00,y=632.00},sct={x=740.71,y=563.08},dct={x=832.75,y=13.24},ends={x=-16.00,y=497.00},duration= 7, section=-1},
}
return fishpath_20_6
