--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_19_3 = {
	{t=1,starts={x=1296.00,y=-5.00},sct={x=1132.27,y=25.95},dct={x=374.94,y=739.11},ends={x=-13.00,y=673.00},duration= 7, section=-1},
}
return fishpath_19_3
