--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_17_4 = {
	{t=1,starts={x=1129.00,y=746.00},sct={x=-102.00,y=538.00},dct={x=529.23,y=-153.97},ends={x=-19.00,y=117.00},duration= 7, section=-1},
}
return fishpath_17_4
