--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_24_1 = {
	{t=1,starts={x=-50.00,y=516.00},sct={x=160.05,y=715.48},dct={x=1162.97,y=349.64},ends={x=719.00,y=-72.00},duration= 7, section=-1},
}
return fishpath_24_1
