--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_5_2 = {
	{t=1,starts={x=-15.00,y=578.00},sct={x=-49.86,y=434.01},dct={x=387.00,y=78.00},ends={x=636.00,y=471.00},duration= 7, section=-1},
	{t=1,starts={x=636.00,y=471.00},sct={x=881.00,y=797.00},dct={x=889.00,y=300.00},ends={x=1311.00,y=209.00},duration= 7, section=-1},
}
return fishpath_5_2
