--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_26_6 = {
	{t=1,starts={x=1093.00,y=751.00},sct={x=1044.24,y=751.01},dct={x=646.35,y=-57.94},ends={x=1060.00,y=-58.00},duration= 7, section=-1},
}
return fishpath_26_6
