--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_20_10 = {
	{t=1,starts={x=439.00,y=-67.00},sct={x=491.00,y=3.00},dct={x=894.00,y=484.00},ends={x=611.00,y=739.00},duration= 7, section=-1},
}
return fishpath_20_10
