--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_24_5 = {
	{t=1,starts={x=1392.00,y=393.00},sct={x=1392.00,y=393.00},dct={x=126.00,y=-77.00},ends={x=126.00,y=-77.00},duration= 20, section=-1},
}
return fishpath_24_5
