--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_22_7 = {
	{t=1,starts={x=1317.00,y=617.00},sct={x=1272.46,y=692.80},dct={x=-51.80,y=174.42},ends={x=93.00,y=-72.00},duration= 7, section=-1},
}
return fishpath_22_7
