--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_21_2 = {
	{t=1,starts={x=-42.00,y=379.00},sct={x=753.87,y=-37.36},dct={x=833.00,y=662.00},ends={x=1310.00,y=558.00},duration= 7, section=-1},
}
return fishpath_21_2
