--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_5_8 = {
	{t=1,starts={x=1312.00,y=325.00},sct={x=888.00,y=128.00},dct={x=39.00,y=480.00},ends={x=6.00,y=728.00},duration= 7, section=-1},
}
return fishpath_5_8
