--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_6_3 = {
	{t=1,starts={x=-36.00,y=79.00},sct={x=88.00,y=410.00},dct={x=475.68,y=418.85},ends={x=800.00,y=137.00},duration= 7, section=-1},
	{t=1,starts={x=800.00,y=137.00},sct={x=1062.00,y=-84.00},dct={x=1020.00,y=395.00},ends={x=804.00,y=508.00},duration= 7, section=-1},
	{t=1,starts={x=804.00,y=508.00},sct={x=574.20,y=635.99},dct={x=-64.97,y=601.36},ends={x=-32.00,y=583.00},duration= 7, section=-1},
}
return fishpath_6_3
