--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_10_7 = {
	{t=1,starts={x=434.00,y=744.00},sct={x=423.00,y=520.00},dct={x=987.00,y=177.00},ends={x=935.00,y=-61.00},duration= 7, section=-1},
}
return fishpath_10_7
