--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_24_2 = {
	{t=1,starts={x=281.00,y=763.00},sct={x=32.83,y=585.30},dct={x=956.00,y=-20.00},ends={x=1153.00,y=-70.00},duration= 7, section=-1},
}
return fishpath_24_2
