--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_14_9 = {
	{t=1,starts={x=226.00,y=756.00},sct={x=-11.25,y=165.43},dct={x=921.00,y=343.00},ends={x=1295.00,y=199.00},duration= 7, section=-1},
}
return fishpath_14_9
