--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_12_8 = {
	{t=1,starts={x=-23.00,y=14.00},sct={x=424.46,y=178.81},dct={x=-151.04,y=259.45},ends={x=877.00,y=754.00},duration= 7, section=-1},
}
return fishpath_12_8
