--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_28_1 = {
	{t=1,starts={x=114.00,y=760.00},sct={x=33.20,y=669.87},dct={x=1236.15,y=-57.62},ends={x=1312.00,y=27.00},duration= 7, section=-1},
}
return fishpath_28_1
