--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_17_10 = {
	{t=1,starts={x=605.00,y=757.00},sct={x=616.55,y=369.68},dct={x=-195.14,y=239.45},ends={x=241.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_17_10
