--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_25_10 = {
	{t=1,starts={x=1344.00,y=5.00},sct={x=1311.93,y=-55.26},dct={x=-119.60,y=507.04},ends={x=-43.00,y=651.00},duration= 7, section=-1},
}
return fishpath_25_10
