--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_18_8 = {
	{t=1,starts={x=358.00,y=761.00},sct={x=1215.00,y=312.00},dct={x=-158.00,y=232.00},ends={x=860.00,y=-67.00},duration= 7, section=-1},
}
return fishpath_18_8
