--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_13_1 = {
	{t=1,starts={x=1173.00,y=754.00},sct={x=1088.00,y=330.00},dct={x=-888.52,y=537.66},ends={x=1000.00,y=-51.00},duration= 7, section=-1},
}
return fishpath_13_1
