--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_24_7 = {
	{t=1,starts={x=808.00,y=741.00},sct={x=599.75,y=587.51},dct={x=1066.57,y=-128.10},ends={x=1315.00,y=55.00},duration= 7, section=-1},
}
return fishpath_24_7
