--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_23_8 = {
	{t=1,starts={x=166.00,y=760.00},sct={x=-16.95,y=282.81},dct={x=1278.69,y=0.77},ends={x=1306.00,y=72.00},duration= 7, section=-1},
}
return fishpath_23_8
