--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_10_6 = {
	{t=1,starts={x=163.00,y=744.00},sct={x=88.92,y=628.47},dct={x=1245.96,y=-11.40},ends={x=1302.00,y=76.00},duration= 7, section=-1},
}
return fishpath_10_6
