--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_13_5 = {
	{t=1,starts={x=79.00,y=-65.00},sct={x=128.00,y=582.00},dct={x=1123.00,y=-67.00},ends={x=1307.00,y=353.00},duration= 7, section=-1},
}
return fishpath_13_5
