--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_6_8 = {
	{t=1,starts={x=779.00,y=757.00},sct={x=790.87,y=759.69},dct={x=1024.00,y=387.00},ends={x=845.00,y=99.00},duration= 7, section=-1},
	{t=1,starts={x=845.00,y=99.00},sct={x=656.00,y=-153.00},dct={x=148.00,y=110.00},ends={x=244.00,y=362.00},duration= 7, section=-1},
	{t=1,starts={x=244.00,y=362.00},sct={x=464.00,y=806.00},dct={x=1032.00,y=400.00},ends={x=1307.00,y=582.00},duration= 7, section=-1},
}
return fishpath_6_8
