--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_21_6 = {
	{t=1,starts={x=1329.00,y=520.00},sct={x=1329.00,y=520.00},dct={x=527.66,y=-97.04},ends={x=-17.00,y=668.00},duration= 7, section=-1},
}
return fishpath_21_6
