--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_24_9 = {
	{t=1,starts={x=238.00,y=760.00},sct={x=25.27,y=666.85},dct={x=883.00,y=-87.00},ends={x=1045.00,y=-72.00},duration= 7, section=-1},
}
return fishpath_24_9
