--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_19_2 = {
	{t=1,starts={x=68.00,y=-47.00},sct={x=300.81,y=495.02},dct={x=1106.78,y=343.78},ends={x=564.00,y=742.00},duration= 7, section=-1},
}
return fishpath_19_2
