--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_11_3 = {
	{t=1,starts={x=-31.00,y=225.00},sct={x=339.00,y=229.00},dct={x=44.00,y=669.00},ends={x=509.00,y=642.00},duration= 7, section=-1},
	{t=1,starts={x=509.00,y=642.00},sct={x=1375.00,y=555.00},dct={x=1504.00,y=79.00},ends={x=594.00,y=-58.00},duration= 7, section=-1},
}
return fishpath_11_3
