--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_2_5 = {
	{t=1,starts={x=1295.00,y=628.00},sct={x=964.00,y=714.00},dct={x=295.64,y=737.59},ends={x=716.00,y=434.00},duration= 7, section=-1},
	{t=1,starts={x=716.00,y=434.00},sct={x=1001.93,y=250.55},dct={x=940.00,y=-21.00},ends={x=625.00,y=96.00},duration= 7, section=-1},
	{t=1,starts={x=625.00,y=96.00},sct={x=200.00,y=264.00},dct={x=-21.00,y=604.00},ends={x=65.00,y=752.00},duration= 7, section=-1},
}
return fishpath_2_5
