--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_11_6 = {
	{t=1,starts={x=-45.00,y=234.00},sct={x=630.00,y=441.00},dct={x=473.36,y=-44.88},ends={x=1158.00,y=741.00},duration= 7, section=-1},
}
return fishpath_11_6
