--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_20_9 = {
	{t=1,starts={x=-52.00,y=38.00},sct={x=953.30,y=603.93},dct={x=1198.71,y=319.75},ends={x=1149.00,y=760.00},duration= 7, section=-1},
}
return fishpath_20_9
