--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_16_2 = {
	{t=1,starts={x=459.00,y=-66.00},sct={x=564.74,y=10.87},dct={x=537.72,y=906.10},ends={x=-14.00,y=505.00},duration= 7, section=-1},
}
return fishpath_16_2
