--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_2_2 = {
	{t=1,starts={x=1300.00,y=393.00},sct={x=1293.47,y=543.56},dct={x=734.00,y=644.00},ends={x=899.00,y=439.00},duration= 7, section=-1},
	{t=1,starts={x=899.00,y=439.00},sct={x=1057.65,y=278.36},dct={x=1017.83,y=-85.35},ends={x=817.00,y=118.00},duration= 7, section=-1},
	{t=1,starts={x=817.00,y=118.00},sct={x=499.00,y=440.00},dct={x=294.00,y=-45.00},ends={x=-31.00,y=338.00},duration= 7, section=-1},
}
return fishpath_2_2
