--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_9_5 = {
	{t=1,starts={x=1009.00,y=740.00},sct={x=1669.61,y=497.67},dct={x=575.29,y=-177.30},ends={x=-28.00,y=44.00},duration= 7, section=-1},
}
return fishpath_9_5
