--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_21_3 = {
	{t=1,starts={x=220.00,y=756.00},sct={x=88.64,y=462.18},dct={x=948.00,y=357.00},ends={x=1092.00,y=-52.00},duration= 7, section=-1},
}
return fishpath_21_3
