--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_24_5 = {
	{t=1,starts={x=1323.00,y=318.00},sct={x=1323.85,y=312.88},dct={x=184.00,y=199.91},ends={x=93.00,y=749.00},duration= 7, section=-1},
}
return fishpath_24_5
