--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_21_9 = {
	{t=1,starts={x=160.00,y=-70.00},sct={x=96.45,y=469.17},dct={x=737.00,y=295.00},ends={x=1311.00,y=616.00},duration= 7, section=-1},
}
return fishpath_21_9
