--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_23_3 = {
	{t=1,starts={x=1132.00,y=754.00},sct={x=840.00,y=708.00},dct={x=37.78,y=100.42},ends={x=221.00,y=-83.00},duration= 7, section=-1},
}
return fishpath_23_3
