--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_4_5 = {
	{t=1,starts={x=-30.00,y=640.00},sct={x=71.00,y=755.00},dct={x=504.00,y=790.00},ends={x=807.00,y=551.00},duration= 7, section=-1},
	{t=1,starts={x=807.00,y=551.00},sct={x=1411.00,y=-15.00},dct={x=74.04,y=-0.10},ends={x=-58.00,y=91.00},duration= 7, section=-1},
}
return fishpath_4_5
