--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_1_4 = {
	{t=1,starts={x=104.00,y=-74.00},sct={x=-54.69,y=87.78},dct={x=266.62,y=239.61},ends={x=381.00,y=123.00},duration= 7, section=-1},
	{t=1,starts={x=381.00,y=123.00},sct={x=672.00,y=-49.00},dct={x=748.00,y=306.00},ends={x=260.00,y=464.00},duration= 7, section=-1},
	{t=1,starts={x=260.00,y=464.00},sct={x=-558.19,y=735.12},dct={x=1130.25,y=659.87},ends={x=1323.00,y=596.00},duration= 7, section=-1},
}
return fishpath_1_4
