--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_26_5 = {
	{t=1,starts={x=240.00,y=747.00},sct={x=255.77,y=750.28},dct={x=641.61,y=11.41},ends={x=327.00,y=-54.00},duration= 7, section=-1},
}
return fishpath_26_5
