--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_16_1 = {
	{t=1,starts={x=1319.00,y=365.00},sct={x=1003.00,y=286.00},dct={x=199.06,y=-212.99},ends={x=-31.00,y=136.00},duration= 7, section=-1},
}
return fishpath_16_1
