--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_16_7 = {
	{t=1,starts={x=1126.00,y=768.00},sct={x=1219.40,y=78.22},dct={x=-843.23,y=1407.63},ends={x=518.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_16_7
