--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_21_10 = {
	{t=1,starts={x=1320.00,y=268.00},sct={x=1311.42,y=229.91},dct={x=226.39,y=269.80},ends={x=331.00,y=734.00},duration= 7, section=-1},
}
return fishpath_21_10
