--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_7_3 = {
	{t=1,starts={x=1303.00,y=119.00},sct={x=1198.00,y=588.00},dct={x=699.00,y=695.00},ends={x=680.00,y=441.00},duration= 7, section=-1},
	{t=1,starts={x=680.00,y=441.00},sct={x=661.00,y=68.00},dct={x=932.00,y=306.00},ends={x=1043.00,y=-59.00},duration= 7, section=-1},
}
return fishpath_7_3
