--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_19_7 = {
	{t=1,starts={x=1301.00,y=207.00},sct={x=1275.00,y=154.00},dct={x=74.25,y=-218.95},ends={x=234.00,y=735.00},duration= 7, section=-1},
}
return fishpath_19_7
