--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_9_1 = {
	{t=1,starts={x=860.00,y=746.00},sct={x=363.74,y=330.43},dct={x=1592.00,y=523.00},ends={x=1167.00,y=275.00},duration= 7, section=-1},
	{t=1,starts={x=1167.00,y=275.00},sct={x=441.00,y=-137.00},dct={x=113.58,y=368.78},ends={x=369.00,y=565.00},duration= 7, section=-1},
	{t=1,starts={x=369.00,y=565.00},sct={x=704.00,y=809.00},dct={x=1002.00,y=26.00},ends={x=791.00,y=-77.00},duration= 7, section=-1},
}
return fishpath_9_1
