--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_9_6 = {
	{t=1,starts={x=1314.00,y=581.00},sct={x=459.00,y=678.00},dct={x=137.00,y=651.00},ends={x=79.00,y=-50.00},duration= 7, section=-1},
}
return fishpath_9_6
