--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_8_5 = {
	{t=1,starts={x=786.00,y=-57.00},sct={x=597.00,y=144.00},dct={x=1034.00,y=240.00},ends={x=1294.00,y=566.00},duration= 7, section=-1},
}
return fishpath_8_5
