--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_24_10 = {
	{t=1,starts={x=1412.00,y=103.00},sct={x=1412.00,y=103.00},dct={x=-149.00,y=681.00},ends={x=-149.00,y=681.00},duration= 25, section=-1},
}
return fishpath_24_10
