--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_13_6 = {
	{t=1,starts={x=241.00,y=-70.00},sct={x=1321.00,y=380.00},dct={x=16.46,y=702.93},ends={x=1297.00,y=641.00},duration= 7, section=-1},
}
return fishpath_13_6
