--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_5_3 = {
	{t=1,starts={x=-20.00,y=97.00},sct={x=1470.42,y=-85.81},dct={x=707.79,y=274.24},ends={x=937.00,y=731.00},duration= 7, section=-1},
}
return fishpath_5_3
