--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_23_7 = {
	{t=1,starts={x=529.00,y=-58.00},sct={x=353.05,y=98.14},dct={x=1194.18,y=714.11},ends={x=1298.00,y=589.00},duration= 7, section=-1},
}
return fishpath_23_7
