--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_20_7 = {
	{t=1,starts={x=1307.00,y=521.00},sct={x=1194.07,y=795.89},dct={x=97.75,y=618.27},ends={x=708.00,y=-53.00},duration= 7, section=-1},
}
return fishpath_20_7
