--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_26_3 = {
	{t=1,starts={x=105.00,y=-71.00},sct={x=61.05,y=-26.59},dct={x=1192.92,y=514.40},ends={x=1320.00,y=386.00},duration= 7, section=-1},
}
return fishpath_26_3
