--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_9_9 = {
	{t=1,starts={x=1302.00,y=663.00},sct={x=1247.00,y=63.00},dct={x=-262.00,y=797.00},ends={x=301.00,y=-52.00},duration= 7, section=-1},
}
return fishpath_9_9
