--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_8_6 = {
	{t=1,starts={x=1019.00,y=-61.00},sct={x=843.00,y=36.00},dct={x=777.00,y=546.00},ends={x=1077.00,y=748.00},duration= 7, section=-1},
}
return fishpath_8_6
