--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_4_6 = {
	{t=1,starts={x=-27.00,y=156.00},sct={x=241.00,y=268.00},dct={x=-97.00,y=644.00},ends={x=282.00,y=560.00},duration= 7, section=-1},
	{t=1,starts={x=282.00,y=560.00},sct={x=741.00,y=465.00},dct={x=667.00,y=673.00},ends={x=890.00,y=461.00},duration= 7, section=-1},
	{t=1,starts={x=890.00,y=461.00},sct={x=1167.00,y=156.00},dct={x=820.00,y=194.00},ends={x=1085.00,y=-63.00},duration= 7, section=-1},
}
return fishpath_4_6
