--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_23_4 = {
	{t=1,starts={x=1200.00,y=766.00},sct={x=1334.51,y=592.99},dct={x=77.62,y=-10.29},ends={x=-48.00,y=149.00},duration= 7, section=-1},
}
return fishpath_23_4
