--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_4_9 = {
	{t=1,starts={x=960.00,y=-57.00},sct={x=1105.00,y=152.00},dct={x=1467.00,y=201.00},ends={x=1196.00,y=358.00},duration= 7, section=-1},
	{t=1,starts={x=1196.00,y=358.00},sct={x=781.00,y=603.00},dct={x=642.00,y=517.00},ends={x=386.00,y=259.00},duration= 7, section=-1},
	{t=1,starts={x=386.00,y=259.00},sct={x=105.00,y=-30.00},dct={x=216.07,y=626.31},ends={x=320.00,y=765.00},duration= 7, section=-1},
}
return fishpath_4_9
