--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_2_8 = {
	{t=1,starts={x=1304.00,y=134.00},sct={x=1143.22,y=-43.26},dct={x=418.00,y=54.00},ends={x=766.00,y=414.00},duration= 7, section=-1},
	{t=1,starts={x=766.00,y=414.00},sct={x=1274.40,y=962.30},dct={x=-35.00,y=470.00},ends={x=-31.00,y=18.00},duration= 7, section=-1},
}
return fishpath_2_8
