--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_24_6 = {
	{t=1,starts={x=1324.00,y=642.00},sct={x=1011.37,y=696.41},dct={x=394.24,y=153.66},ends={x=606.00,y=-55.00},duration= 7, section=-1},
}
return fishpath_24_6
