--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_2_9 = {
	{t=1,starts={x=1097.00,y=745.00},sct={x=905.29,y=594.33},dct={x=1205.80,y=415.51},ends={x=913.00,y=215.00},duration= 7, section=-1},
	{t=1,starts={x=913.00,y=215.00},sct={x=651.00,y=60.00},dct={x=-19.56,y=-21.54},ends={x=-25.00,y=229.00},duration= 7, section=-1},
}
return fishpath_2_9
