--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_18_7 = {
	{t=1,starts={x=-23.00,y=101.00},sct={x=346.24,y=-9.75},dct={x=779.00,y=517.00},ends={x=1299.00,y=556.00},duration= 7, section=-1},
}
return fishpath_18_7
