--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_18_10 = {
	{t=1,starts={x=1124.00,y=735.00},sct={x=867.00,y=675.00},dct={x=682.06,y=-105.31},ends={x=1071.00,y=-50.00},duration= 7, section=-1},
}
return fishpath_18_10
