--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_1_3 = {
	{t=1,starts={x=-26.00,y=591.00},sct={x=-80.18,y=449.45},dct={x=102.00,y=222.00},ends={x=272.00,y=312.00},duration= 7, section=-1},
	{t=1,starts={x=272.00,y=312.00},sct={x=487.00,y=442.00},dct={x=497.22,y=752.92},ends={x=623.00,y=582.00},duration= 7, section=-1},
	{t=1,starts={x=623.00,y=582.00},sct={x=702.00,y=387.00},dct={x=884.00,y=247.00},ends={x=989.00,y=363.00},duration= 7, section=-1},
	{t=1,starts={x=989.00,y=363.00},sct={x=1322.60,y=677.32},dct={x=1241.00,y=-63.00},ends={x=863.00,y=-74.00},duration= 7, section=-1},
}
return fishpath_1_3
