--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_26_8 = {
	{t=1,starts={x=1150.00,y=747.00},sct={x=1174.71,y=724.24},dct={x=182.41,y=9.19},ends={x=-28.00,y=203.00},duration= 7, section=-1},
}
return fishpath_26_8
