--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_8_10 = {
	{t=1,starts={x=-30.00,y=639.00},sct={x=169.00,y=249.00},dct={x=274.00,y=251.00},ends={x=752.00,y=33.00},duration= 7, section=-1},
	{t=1,starts={x=752.00,y=33.00},sct={x=1147.00,y=-130.00},dct={x=1358.71,y=363.25},ends={x=1187.00,y=511.00},duration= 7, section=-1},
	{t=1,starts={x=1187.00,y=511.00},sct={x=882.00,y=698.00},dct={x=278.00,y=627.00},ends={x=59.00,y=-67.00},duration= 7, section=-1},
}
return fishpath_8_10
