--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_22_8 = {
	{t=1,starts={x=-48.00,y=477.00},sct={x=345.40,y=713.01},dct={x=1083.63,y=8.77},ends={x=964.00,y=-63.00},duration= 7, section=-1},
}
return fishpath_22_8
