--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_25_9 = {
	{t=1,starts={x=-39.00,y=72.00},sct={x=-63.51,y=153.62},dct={x=1269.07,y=744.30},ends={x=1307.00,y=618.00},duration= 7, section=-1},
}
return fishpath_25_9
