--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_1_5 = {
	{t=1,starts={x=1319.00,y=-18.00},sct={x=1366.31,y=47.18},dct={x=965.00,y=431.00},ends={x=517.00,y=241.00},duration= 7, section=-1},
	{t=1,starts={x=517.00,y=241.00},sct={x=113.00,y=98.00},dct={x=52.90,y=650.67},ends={x=274.00,y=777.00},duration= 7, section=-1},
}
return fishpath_1_5
