--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_13_7 = {
	{t=1,starts={x=1326.00,y=92.00},sct={x=273.00,y=394.00},dct={x=1128.00,y=730.00},ends={x=-26.00,y=593.00},duration= 7, section=-1},
}
return fishpath_13_7
