--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_5_4 = {
	{t=1,starts={x=236.00,y=-65.00},sct={x=2200.44,y=290.06},dct={x=230.00,y=422.00},ends={x=529.00,y=740.00},duration= 7, section=-1},
}
return fishpath_5_4
