--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_24_4 = {
	{t=1,starts={x=1076.00,y=-120.00},sct={x=1076.00,y=-120.00},dct={x=243.00,y=820.00},ends={x=243.00,y=820.00},duration=21, section=-1},
}
return fishpath_24_4
