--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_10_5 = {
	{t=1,starts={x=1317.00,y=560.00},sct={x=243.00,y=561.00},dct={x=11.00,y=389.00},ends={x=285.00,y=53.00},duration= 7, section=-1},
	{t=1,starts={x=285.00,y=53.00},sct={x=653.48,y=-345.35},dct={x=835.00,y=510.00},ends={x=1178.00,y=740.00},duration= 7, section=-1},
}
return fishpath_10_5
