--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_7_1 = {
	{t=1,starts={x=595.00,y=746.00},sct={x=1484.00,y=257.00},dct={x=731.00,y=375.00},ends={x=-23.00,y=-30.00},duration= 7, section=-1},
}
return fishpath_7_1
