--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_17_3 = {
	{t=1,starts={x=479.00,y=752.00},sct={x=-271.00,y=288.00},dct={x=997.00,y=245.00},ends={x=646.00,y=-54.00},duration= 7, section=-1},
}
return fishpath_17_3
