--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_4_1 = {
	{t=1,starts={x=-20.00,y=743.00},sct={x=34.00,y=182.00},dct={x=1142.00,y=479.00},ends={x=1291.00,y=-45.00},duration= 7, section=-1},
}
return fishpath_4_1
