--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_16_5 = {
	{t=1,starts={x=1310.00,y=532.00},sct={x=-554.33,y=1053.73},dct={x=96.00,y=-53.00},ends={x=523.00,y=-45.00},duration= 7, section=-1},
}
return fishpath_16_5
