--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_1_2 = {
	{t=1,starts={x=-2.00,y=787.00},sct={x=-67.15,y=767.73},dct={x=180.40,y=174.79},ends={x=411.00,y=243.00},duration= 7, section=-1},
	{t=1,starts={x=411.00,y=243.00},sct={x=713.00,y=359.00},dct={x=707.00,y=144.00},ends={x=932.00,y=226.00},duration= 7, section=-1},
	{t=1,starts={x=932.00,y=226.00},sct={x=1219.00,y=343.00},dct={x=1320.33,y=789.43},ends={x=1258.00,y=800.00},duration= 7, section=-1},
}
return fishpath_1_2
