--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_18_9 = {
	{t=1,starts={x=1335.00,y=213.00},sct={x=1013.87,y=135.66},dct={x=251.35,y=683.14},ends={x=259.00,y=752.00},duration= 7, section=-1},
}
return fishpath_18_9
