--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_11_7 = {
	{t=1,starts={x=-23.00,y=18.00},sct={x=1928.46,y=41.91},dct={x=882.00,y=101.00},ends={x=834.00,y=738.00},duration= 7, section=-1},
}
return fishpath_11_7
