--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_25_2 = {
	{t=1,starts={x=494.00,y=755.00},sct={x=517.97,y=753.65},dct={x=563.61,y=-73.32},ends={x=451.00,y=-67.00},duration= 7, section=-1},
}
return fishpath_25_2
