--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_15_8 = {
	{t=1,starts={x=-45.00,y=163.00},sct={x=1173.00,y=573.00},dct={x=447.00,y=31.00},ends={x=1299.00,y=13.00},duration= 7, section=-1},
}
return fishpath_15_8
