--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_22_3 = {
	{t=1,starts={x=-49.00,y=173.00},sct={x=434.59,y=-20.59},dct={x=1149.00,y=615.00},ends={x=1308.00,y=641.00},duration= 7, section=-1},
}
return fishpath_22_3
