--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_8_4 = {
	{t=1,starts={x=1293.00,y=-15.00},sct={x=773.00,y=96.00},dct={x=1085.00,y=357.00},ends={x=535.00,y=310.00},duration= 7, section=-1},
	{t=1,starts={x=535.00,y=310.00},sct={x=244.18,y=279.12},dct={x=232.00,y=724.25},ends={x=597.00,y=763.00},duration= 7, section=-1},
}
return fishpath_8_4
