--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_15_4 = {
	{t=1,starts={x=1308.00,y=171.00},sct={x=1312.43,y=261.51},dct={x=358.77,y=769.44},ends={x=338.00,y=345.00},duration= 7, section=-1},
	{t=1,starts={x=338.00,y=345.00},sct={x=314.18,y=26.62},dct={x=876.00,y=132.00},ends={x=1047.00,y=-53.00},duration= 7, section=-1},
}
return fishpath_15_4
