--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_4_8 = {
	{t=1,starts={x=1342.00,y=600.00},sct={x=763.00,y=442.00},dct={x=332.00,y=764.00},ends={x=306.00,y=534.00},duration= 7, section=-1},
	{t=1,starts={x=306.00,y=534.00},sct={x=262.00,y=124.00},dct={x=-27.00,y=96.00},ends={x=373.00,y=-54.00},duration= 7, section=-1},
}
return fishpath_4_8
