--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_3_2 = {
	{t=1,starts={x=866.00,y=759.00},sct={x=901.00,y=554.00},dct={x=577.70,y=357.19},ends={x=326.00,y=620.00},duration= 7, section=-1},
	{t=1,starts={x=326.00,y=620.00},sct={x=159.00,y=798.00},dct={x=-232.77,y=514.80},ends={x=386.00,y=250.00},duration= 7, section=-1},
	{t=1,starts={x=386.00,y=250.00},sct={x=939.00,y=43.00},dct={x=709.00,y=717.00},ends={x=1041.00,y=303.00},duration= 7, section=-1},
	{t=1,starts={x=1041.00,y=303.00},sct={x=1172.00,y=154.00},dct={x=1038.00,y=156.00},ends={x=1304.00,y=40.00},duration= 7, section=-1},
}
return fishpath_3_2
