--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_23_6 = {
	{t=1,starts={x=1311.00,y=402.00},sct={x=1271.61,y=305.78},dct={x=296.95,y=571.35},ends={x=366.00,y=740.00},duration= 7, section=-1},
}
return fishpath_23_6
