--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_19_5 = {
	{t=1,starts={x=1329.00,y=187.00},sct={x=961.00,y=57.00},dct={x=-22.57,y=555.90},ends={x=341.00,y=747.00},duration= 7, section=-1},
}
return fishpath_19_5
