--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_17_5 = {
	{t=1,starts={x=1331.00,y=200.00},sct={x=609.00,y=-185.00},dct={x=594.00,y=192.00},ends={x=-50.00,y=485.00},duration= 7, section=-1},
}
return fishpath_17_5
