--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_24_8 = {
	{t=1,starts={x=1306.00,y=596.00},sct={x=1405.87,y=382.21},dct={x=63.03,y=138.72},ends={x=-31.00,y=340.00},duration= 7, section=-1},
}
return fishpath_24_8
