--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_1_10 = {
	{t=1,starts={x=237.00,y=754.00},sct={x=-22.00,y=331.00},dct={x=381.00,y=615.00},ends={x=864.00,y=470.00},duration= 7, section=-1},
	{t=1,starts={x=864.00,y=470.00},sct={x=1284.41,y=324.30},dct={x=595.29,y=134.03},ends={x=252.00,y=253.00},duration= 7, section=-1},
	{t=1,starts={x=252.00,y=253.00},sct={x=48.00,y=316.00},dct={x=-64.00,y=31.00},ends={x=805.00,y=-66.00},duration= 7, section=-1},
}
return fishpath_1_10
