--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_21_4 = {
	{t=1,starts={x=1338.00,y=604.00},sct={x=216.81,y=551.48},dct={x=403.40,y=-3.37},ends={x=-42.00,y=14.00},duration= 7, section=-1},
}
return fishpath_21_4
