--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_14_2 = {
	{t=1,starts={x=178.00,y=-68.00},sct={x=20.61,y=328.18},dct={x=830.99,y=21.95},ends={x=486.00,y=462.00},duration= 7, section=-1},
	{t=1,starts={x=486.00,y=462.00},sct={x=132.89,y=930.92},dct={x=1307.36,y=518.68},ends={x=1308.00,y=518.00},duration= 7, section=-1},
}
return fishpath_14_2
