--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_19_4 = {
	{t=1,starts={x=-41.00,y=84.00},sct={x=798.40,y=-27.33},dct={x=496.00,y=419.00},ends={x=1213.00,y=758.00},duration= 7, section=-1},
}
return fishpath_19_4
