--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_6_4 = {
	{t=1,starts={x=176.00,y=747.00},sct={x=76.25,y=671.09},dct={x=75.00,y=-143.00},ends={x=383.00,y=175.00},duration= 7, section=-1},
	{t=1,starts={x=383.00,y=175.00},sct={x=620.00,y=426.00},dct={x=766.00,y=397.00},ends={x=952.00,y=222.00},duration= 7, section=-1},
	{t=1,starts={x=952.00,y=222.00},sct={x=1286.00,y=-97.00},dct={x=1298.00,y=531.00},ends={x=970.00,y=757.00},duration= 7, section=-1},
}
return fishpath_6_4
