--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_1_7 = {
	{t=1,starts={x=399.00,y=764.00},sct={x=239.00,y=596.00},dct={x=609.00,y=604.00},ends={x=937.00,y=510.00},duration= 7, section=-1},
	{t=1,starts={x=937.00,y=510.00},sct={x=1273.00,y=419.00},dct={x=656.00,y=4.00},ends={x=491.00,y=338.00},duration= 7, section=-1},
	{t=1,starts={x=491.00,y=338.00},sct={x=368.71,y=598.39},dct={x=358.00,y=601.00},ends={x=264.00,y=474.00},duration= 7, section=-1},
	{t=1,starts={x=264.00,y=474.00},sct={x=84.00,y=228.00},dct={x=5.00,y=-6.00},ends={x=142.00,y=-75.00},duration= 7, section=-1},
}
return fishpath_1_7
