--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_5_10 = {
	{t=1,starts={x=-37.00,y=380.00},sct={x=74.31,y=437.21},dct={x=37.00,y=126.00},ends={x=207.00,y=97.00},duration= 7, section=-1},
	{t=1,starts={x=207.00,y=97.00},sct={x=1210.00,y=-43.00},dct={x=576.51,y=414.25},ends={x=1322.00,y=528.00},duration= 7, section=-1},
}
return fishpath_5_10
