--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_7_7 = {
	{t=1,starts={x=173.00,y=-67.00},sct={x=611.00,y=324.00},dct={x=1407.84,y=353.67},ends={x=377.00,y=742.00},duration= 7, section=-1},
}
return fishpath_7_7
