--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_18_5 = {
	{t=1,starts={x=1006.00,y=-52.00},sct={x=1076.00,y=13.00},dct={x=381.44,y=511.19},ends={x=170.00,y=739.00},duration= 7, section=-1},
}
return fishpath_18_5
