--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_20_8 = {
	{t=1,starts={x=1093.00,y=752.00},sct={x=1330.45,y=-11.66},dct={x=1.11,y=528.84},ends={x=303.00,y=-53.00},duration= 7, section=-1},
}
return fishpath_20_8
