--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_27_2 = {
	{t=1,starts={x=1329.00,y=17.00},sct={x=1339.00,y=148.00},dct={x=196.75,y=775.96},ends={x=-34.00,y=608.00},duration= 7, section=-1},
}
return fishpath_27_2
