--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_27_1 = {
	{t=1,starts={x=-43.00,y=50.00},sct={x=-72.00,y=163.00},dct={x=1194.72,y=725.19},ends={x=1307.00,y=579.00},duration= 7, section=-1},
}
return fishpath_27_1
