--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_24_10 = {
	{t=1,starts={x=-43.00,y=70.00},sct={x=140.27,y=26.97},dct={x=1294.00,y=404.00},ends={x=1318.00,y=611.00},duration= 7, section=-1},
}
return fishpath_24_10
