--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_23_9 = {
	{t=1,starts={x=-31.00,y=322.00},sct={x=-32.00,y=406.00},dct={x=1265.13,y=755.08},ends={x=1313.00,y=566.00},duration= 7, section=-1},
}
return fishpath_23_9
