--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_2_3 = {
	{t=1,starts={x=1303.00,y=254.00},sct={x=1209.78,y=687.83},dct={x=915.00,y=844.00},ends={x=742.00,y=647.00},duration= 7, section=-1},
	{t=1,starts={x=742.00,y=647.00},sct={x=543.09,y=350.20},dct={x=684.00,y=-53.00},ends={x=904.00,y=-81.00},duration= 7, section=-1},
}
return fishpath_2_3
