--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_22_2 = {
	{t=1,starts={x=1305.00,y=671.00},sct={x=1317.46,y=624.91},dct={x=612.67,y=-162.86},ends={x=366.00,y=750.00},duration= 7, section=-1},
}
return fishpath_22_2
