--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_13_8 = {
	{t=1,starts={x=-25.00,y=343.00},sct={x=188.85,y=356.47},dct={x=1168.22,y=519.74},ends={x=1307.00,y=335.00},duration= 7, section=-1},
}
return fishpath_13_8
