--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_8_8 = {
	{t=1,starts={x=1292.00,y=547.00},sct={x=721.00,y=617.00},dct={x=875.00,y=72.00},ends={x=279.00,y=160.00},duration= 7, section=-1},
	{t=1,starts={x=279.00,y=160.00},sct={x=-49.00,y=210.00},dct={x=186.18,y=695.19},ends={x=569.00,y=619.00},duration= 7, section=-1},
	{t=1,starts={x=569.00,y=619.00},sct={x=1062.00,y=484.00},dct={x=1058.36,y=-70.59},ends={x=1041.00,y=-69.00},duration= 7, section=-1},
}
return fishpath_8_8
