--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_16_4 = {
	{t=1,starts={x=1049.00,y=774.00},sct={x=1265.04,y=182.20},dct={x=-177.86,y=263.06},ends={x=529.00,y=-82.00},duration= 7, section=-1},
}
return fishpath_16_4
