--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 17:02:07
local fishpath_2_6 = {
	{t=1,starts={x=-27.00,y=307.00},sct={x=-7.09,y=92.97},dct={x=487.00,y=-7.00},ends={x=511.00,y=340.00},duration= 7, section=-1},
	{t=1,starts={x=511.00,y=340.00},sct={x=560.00,y=642.00},dct={x=703.00,y=712.00},ends={x=845.00,y=641.00},duration= 7, section=-1},
	{t=1,starts={x=845.00,y=641.00},sct={x=1210.00,y=474.00},dct={x=884.00,y=111.00},ends={x=1298.00,y=125.00},duration= 7, section=-1},
}
return fishpath_2_6
