--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_14_1 = {
	{t=1,starts={x=1128.00,y=-56.00},sct={x=1475.00,y=656.00},dct={x=-619.32,y=148.07},ends={x=528.00,y=744.00},duration= 7, section=-1},
}
return fishpath_14_1
