--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_9_8 = {
	{t=1,starts={x=-31.00,y=90.00},sct={x=1738.40,y=13.66},dct={x=-111.00,y=598.00},ends={x=892.00,y=741.00},duration= 7, section=-1},
}
return fishpath_9_8
