--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_10_4 = {
	{t=1,starts={x=-29.00,y=286.00},sct={x=885.00,y=14.00},dct={x=1241.20,y=-37.33},ends={x=916.00,y=534.00},duration= 7, section=-1},
	{t=1,starts={x=916.00,y=534.00},sct={x=766.00,y=808.00},dct={x=-145.00,y=583.00},ends={x=1298.00,y=167.00},duration= 7, section=-1},
}
return fishpath_10_4
