--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_26_4 = {
	{t=1,starts={x=-53.00,y=617.00},sct={x=59.45,y=689.30},dct={x=1230.00,y=125.00},ends={x=1138.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_26_4
