--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_20_1 = {
	{t=1,starts={x=1334.00,y=505.00},sct={x=1033.17,y=604.57},dct={x=611.44,y=110.42},ends={x=96.00,y=-68.00},duration= 7, section=-1},
}
return fishpath_20_1
