--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_22_9 = {
	{t=1,starts={x=1318.00,y=569.00},sct={x=1125.00,y=648.00},dct={x=79.90,y=295.79},ends={x=251.00,y=-70.00},duration= 7, section=-1},
}
return fishpath_22_9
