--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_4_2 = {
	{t=1,starts={x=993.00,y=755.00},sct={x=1253.00,y=-131.00},dct={x=-210.00,y=784.00},ends={x=289.00,y=-67.00},duration= 7, section=-1},
}
return fishpath_4_2
