--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_25_7 = {
	{t=1,starts={x=156.00,y=778.00},sct={x=3.69,y=572.69},dct={x=806.76,y=237.28},ends={x=919.00,y=-82.00},duration= 7, section=-1},
}
return fishpath_25_7
