--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_10_10 = {
	{t=1,starts={x=-20.00,y=205.00},sct={x=255.00,y=66.00},dct={x=1219.00,y=366.00},ends={x=1070.00,y=755.00},duration= 7, section=-1},
}
return fishpath_10_10
