--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_12_6 = {
	{t=1,starts={x=-17.00,y=592.00},sct={x=1230.00,y=459.00},dct={x=1354.92,y=979.21},ends={x=1151.00,y=-51.00},duration= 7, section=-1},
}
return fishpath_12_6
