--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_24_3 = {
	{t=1,starts={x=1326.00,y=435.00},sct={x=1326.08,y=456.59},dct={x=-39.18,y=299.39},ends={x=-40.00,y=70.00},duration= 7, section=-1},
}
return fishpath_24_3
