--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_11_1 = {
	{t=1,starts={x=-32.00,y=351.00},sct={x=-19.63,y=298.54},dct={x=660.00,y=78.00},ends={x=664.00,y=405.00},duration= 7, section=-1},
	{t=1,starts={x=664.00,y=405.00},sct={x=659.00,y=696.00},dct={x=1191.00,y=577.00},ends={x=1333.00,y=342.00},duration= 7, section=-1},
}
return fishpath_11_1
