--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 10:44:52
local fishpath_4_3 = {
	{t=1,starts={x=1362.00,y=560.00},sct={x=995.00,y=90.00},dct={x=357.76,y=-312.24},ends={x=-31.00,y=663.00},duration= 7, section=-1},
}
return fishpath_4_3
