--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_2_4 = {
	{t=1,starts={x=1303.00,y=106.00},sct={x=1139.07,y=356.66},dct={x=519.00,y=-174.77},ends={x=416.00,y=144.00},duration= 7, section=-1},
	{t=1,starts={x=416.00,y=144.00},sct={x=306.00,y=553.00},dct={x=885.94,y=343.82},ends={x=812.00,y=751.00},duration= 7, section=-1},
}
return fishpath_2_4
