--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_10_9 = {
	{t=1,starts={x=-39.00,y=551.00},sct={x=-37.96,y=450.51},dct={x=1306.00,y=371.00},ends={x=1316.00,y=597.00},duration= 7, section=-1},
}
return fishpath_10_9
