--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_9_10 = {
	{t=1,starts={x=-36.00,y=102.00},sct={x=1496.00,y=95.00},dct={x=-68.00,y=426.00},ends={x=903.00,y=747.00},duration= 7, section=-1},
}
return fishpath_9_10
