--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-24-16 20:23:53
local fishpath_17_1 = {
	{t=1,starts={x=1320.00,y=548.00},sct={x=994.00,y=524.00},dct={x=1232.00,y=53.00},ends={x=944.00,y=-19.00},duration= 7, section=-1},
	{t=1,starts={x=944.00,y=-19.00},sct={x=550.87,y=-77.21},dct={x=307.52,y=658.24},ends={x=988.00,y=759.00},duration= 7, section=-1},
}
return fishpath_17_1
