--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_7_10 = {
	{t=1,starts={x=1300.00,y=672.00},sct={x=1165.00,y=498.00},dct={x=1225.00,y=8.00},ends={x=938.00,y=-9.00},duration= 7, section=-1},
	{t=1,starts={x=938.00,y=-9.00},sct={x=276.00,y=-27.00},dct={x=217.00,y=411.00},ends={x=390.00,y=745.00},duration= 7, section=-1},
}
return fishpath_7_10
