--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_5_1 = {
	{t=1,starts={x=219.00,y=-59.00},sct={x=104.28,y=-82.86},dct={x=-31.00,y=295.00},ends={x=482.00,y=419.00},duration= 7, section=-1},
	{t=1,starts={x=482.00,y=419.00},sct={x=1249.00,y=569.00},dct={x=590.00,y=589.00},ends={x=1079.00,y=757.00},duration= 7, section=-1},
}
return fishpath_5_1
