--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_13_2 = {
	{t=1,starts={x=-33.00,y=129.00},sct={x=498.00,y=202.00},dct={x=260.14,y=1219.63},ends={x=865.00,y=270.00},duration= 7, section=-1},
	{t=1,starts={x=865.00,y=270.00},sct={x=1090.00,y=-60.00},dct={x=1392.06,y=594.13},ends={x=1155.00,y=749.00},duration= 7, section=-1},
}
return fishpath_13_2
