--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_5_9 = {
	{t=1,starts={x=1321.00,y=684.00},sct={x=1124.00,y=782.00},dct={x=549.00,y=676.00},ends={x=319.00,y=413.00},duration= 7, section=-1},
	{t=1,starts={x=319.00,y=413.00},sct={x=41.00,y=104.00},dct={x=308.00,y=140.00},ends={x=399.00,y=-62.00},duration= 7, section=-1},
}
return fishpath_5_9
