--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_26_2 = {
	{t=1,starts={x=1314.00,y=39.00},sct={x=1300.33,y=-24.33},dct={x=162.27,y=460.68},ends={x=226.00,y=756.00},duration= 7, section=-1},
}
return fishpath_26_2
