--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_10_8 = {
	{t=1,starts={x=1316.00,y=674.00},sct={x=791.00,y=209.00},dct={x=338.00,y=309.00},ends={x=94.00,y=-53.00},duration= 7, section=-1},
}
return fishpath_10_8
