--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_6_9 = {
	{t=1,starts={x=1302.00,y=530.00},sct={x=632.00,y=354.00},dct={x=492.00,y=-152.00},ends={x=396.00,y=213.00},duration= 7, section=-1},
	{t=1,starts={x=396.00,y=213.00},sct={x=268.00,y=731.00},dct={x=453.00,y=465.00},ends={x=1027.00,y=746.00},duration= 7, section=-1},
}
return fishpath_6_9
