--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_6_1 = {
	{t=1,starts={x=1138.00,y=752.00},sct={x=1262.00,y=446.00},dct={x=1173.00,y=459.00},ends={x=786.00,y=163.00},duration= 7, section=-1},
	{t=1,starts={x=786.00,y=163.00},sct={x=278.00,y=-156.00},dct={x=521.00,y=299.00},ends={x=-37.00,y=380.00},duration= 7, section=-1},
}
return fishpath_6_1
