--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_7_5 = {
	{t=1,starts={x=1297.00,y=278.00},sct={x=1170.00,y=155.00},dct={x=1324.00,y=-84.00},ends={x=1085.00,y=16.00},duration= 7, section=-1},
	{t=1,starts={x=1085.00,y=16.00},sct={x=582.53,y=249.17},dct={x=612.00,y=416.00},ends={x=-19.00,y=692.00},duration= 7, section=-1},
}
return fishpath_7_5
