--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_32_3 = {
	{t=1,starts={x=680.00,y=-130.00},sct={x=680.00,y=-130.00},dct={x=923.00,y=310.00},ends={x=1400.00,y=362.00},duration= 7, section=-1},
}
return fishpath_32_3
