--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_10_2 = {
	{t=1,starts={x=686.00,y=727.00},sct={x=-212.00,y=157.00},dct={x=1095.00,y=559.00},ends={x=1134.00,y=-50.00},duration= 7, section=-1},
}
return fishpath_10_2
