--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_10_1 = {
	{t=1,starts={x=236.00,y=749.00},sct={x=-2.00,y=572.00},dct={x=1552.00,y=181.00},ends={x=270.00,y=-59.00},duration= 7, section=-1},
}
return fishpath_10_1
