--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_1_6 = {
	{t=1,starts={x=774.00,y=-87.00},sct={x=1144.00,y=-39.00},dct={x=1357.16,y=173.24},ends={x=1073.00,y=278.00},duration= 7, section=-1},
	{t=1,starts={x=1073.00,y=278.00},sct={x=751.00,y=449.00},dct={x=1018.00,y=731.00},ends={x=625.00,y=569.00},duration= 7, section=-1},
	{t=1,starts={x=625.00,y=569.00},sct={x=306.00,y=426.00},dct={x=-36.00,y=79.00},ends={x=87.00,y=-51.00},duration= 7, section=-1},
}
return fishpath_1_6
