--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_33_4 = {
	{t=1,starts={x=1518.67,y=736.00},sct={x=1092.00,y=-8.00},dct={x=282.67,y=-14.67},ends={x=-246.67,y=409.33},duration= 7, section=-1},
}
return fishpath_33_4
