--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_12_5 = {
	{t=1,starts={x=-33.00,y=150.00},sct={x=727.33,y=919.88},dct={x=407.00,y=276.00},ends={x=1285.00,y=-22.00},duration= 7, section=-1},
}
return fishpath_12_5
