--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_8_2 = {
	{t=1,starts={x=-20.00,y=44.00},sct={x=194.00,y=535.00},dct={x=-68.00,y=570.00},ends={x=190.00,y=642.00},duration= 7, section=-1},
	{t=1,starts={x=190.00,y=642.00},sct={x=364.00,y=691.00},dct={x=769.22,y=481.91},ends={x=652.00,y=735.00},duration= 7, section=-1},
}
return fishpath_8_2
