--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_19_6 = {
	{t=1,starts={x=1331.00,y=502.00},sct={x=1287.75,y=574.70},dct={x=134.94,y=118.97},ends={x=242.00,y=-61.00},duration= 7, section=-1},
}
return fishpath_19_6
