--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_11_10 = {
	{t=1,starts={x=-25.00,y=118.00},sct={x=523.00,y=553.00},dct={x=882.00,y=-126.00},ends={x=1300.00,y=413.00},duration= 7, section=-1},
}
return fishpath_11_10
