--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_18_6 = {
	{t=1,starts={x=1075.00,y=741.00},sct={x=1317.61,y=225.31},dct={x=139.17,y=605.40},ends={x=216.00,y=-80.00},duration= 7, section=-1},
}
return fishpath_18_6
