--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_5_7 = {
	{t=1,starts={x=710.00,y=746.00},sct={x=589.00,y=415.00},dct={x=276.00,y=298.00},ends={x=-40.00,y=411.00},duration= 7, section=-1},
}
return fishpath_5_7
