--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_32_5 = {
	{t=1,starts={x=1320.00,y=917.33},sct={x=1317.33,y=741.33},dct={x=1212.00,y=133.33},ends={x=793.33,y=308.00},duration= 7, section=-1},
	{t=1,starts={x=793.33,y=308.00},sct={x=485.10,y=465.27},dct={x=405.33,y=385.33},ends={x=270.67,y=284.00},duration= 7, section=-1},
	{t=1,starts={x=270.67,y=284.00},sct={x=-85.33,y=17.33},dct={x=-137.33,y=436.00},ends={x=-137.33,y=436.00},duration= 7, section=-1},
}
return fishpath_32_5
