--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_15_1 = {
	{t=1,starts={x=292.00,y=743.00},sct={x=588.81,y=675.30},dct={x=1405.87,y=-15.16},ends={x=730.00,y=139.00},duration= 7, section=-1},
	{t=1,starts={x=730.00,y=139.00},sct={x=-197.73,y=397.67},dct={x=1062.61,y=735.80},ends={x=1295.00,y=672.00},duration= 7, section=-1},
}
return fishpath_15_1
