--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_7_4 = {
	{t=1,starts={x=204.00,y=-56.00},sct={x=-21.00,y=587.00},dct={x=190.67,y=819.19},ends={x=408.00,y=591.00},duration= 7, section=-1},
	{t=1,starts={x=408.00,y=591.00},sct={x=759.74,y=217.62},dct={x=1227.00,y=442.00},ends={x=1113.00,y=737.00},duration= 7, section=-1},
}
return fishpath_7_4
