--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_7_9 = {
	{t=1,starts={x=1287.00,y=490.00},sct={x=1092.00,y=484.00},dct={x=908.00,y=684.00},ends={x=892.00,y=333.00},duration= 7, section=-1},
	{t=1,starts={x=892.00,y=333.00},sct={x=866.00,y=17.00},dct={x=554.00,y=29.00},ends={x=310.00,y=155.00},duration= 7, section=-1},
	{t=1,starts={x=310.00,y=155.00},sct={x=106.00,y=282.00},dct={x=62.00,y=365.00},ends={x=341.00,y=742.00},duration= 7, section=-1},
}
return fishpath_7_9
