--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_5_5 = {
	{t=1,starts={x=1253.00,y=-58.00},sct={x=26.33,y=73.06},dct={x=1581.39,y=869.14},ends={x=-29.00,y=499.00},duration= 7, section=-1},
}
return fishpath_5_5
