--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_6_10 = {
	{t=1,starts={x=909.00,y=739.00},sct={x=765.00,y=605.00},dct={x=791.00,y=82.00},ends={x=989.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_6_10
