--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_24_7 = {
	{t=1,starts={x=911.00,y=833.00},sct={x=911.00,y=833.00},dct={x=273.00,y=-84.00},ends={x=273.00,y=-84.00},duration= 7, section=-1},
}
return fishpath_24_7
