--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_24_1 = {
	{t=1,starts={x=-141.00,y=405.00},sct={x=-141.00,y=405.00},dct={x=1372.00,y=546.00},ends={x=1372.00,y=546.00},duration= 7, section=-1},
}
return fishpath_24_1
