--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_17_8 = {
	{t=1,starts={x=1304.00,y=541.00},sct={x=1285.00,y=455.00},dct={x=76.16,y=319.10},ends={x=-50.00,y=520.00},duration= 7, section=-1},
}
return fishpath_17_8
