--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_33_1 = {
	{t=1,starts={x=-286.67,y=-17.33},sct={x=294.67,y=658.67},dct={x=1050.67,y=-110.67},ends={x=1190.67,y=964.00},duration= 7, section=-1},
}
return fishpath_33_1
