--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_26_7 = {
	{t=1,starts={x=1331.00,y=66.00},sct={x=1315.86,y=16.86},dct={x=425.93,y=465.87},ends={x=519.00,y=768.00},duration= 7, section=-1},
}
return fishpath_26_7
