--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_14_3 = {
	{t=1,starts={x=1303.00,y=86.00},sct={x=599.00,y=384.00},dct={x=1058.00,y=435.00},ends={x=605.00,y=569.00},duration= 7, section=-1},
	{t=1,starts={x=605.00,y=569.00},sct={x=374.00,y=638.00},dct={x=-338.69,y=243.91},ends={x=235.00,y=-52.00},duration= 7, section=-1},
}
return fishpath_14_3
