--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_25_6 = {
	{t=1,starts={x=-44.00,y=337.00},sct={x=57.57,y=676.50},dct={x=1186.23,y=666.79},ends={x=1324.00,y=401.00},duration= 7, section=-1},
}
return fishpath_25_6
