--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_4_10 = {
	{t=1,starts={x=-24.00,y=89.00},sct={x=32.78,y=22.18},dct={x=257.00,y=59.00},ends={x=343.00,y=559.00},duration= 7, section=-1},
	{t=1,starts={x=343.00,y=559.00},sct={x=403.55,y=991.33},dct={x=671.00,y=212.00},ends={x=870.00,y=8.00},duration= 7, section=-1},
	{t=1,starts={x=870.00,y=8.00},sct={x=1200.04,y=-308.32},dct={x=1296.00,y=456.00},ends={x=1057.00,y=754.00},duration= 7, section=-1},
}
return fishpath_4_10
