--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_1_9 = {
	{t=1,starts={x=-33.00,y=475.00},sct={x=-30.00,y=163.00},dct={x=393.00,y=724.00},ends={x=591.00,y=475.00},duration= 7, section=-1},
	{t=1,starts={x=591.00,y=475.00},sct={x=774.48,y=250.28},dct={x=313.07,y=140.32},ends={x=979.00,y=-63.00},duration= 7, section=-1},
}
return fishpath_1_9
