--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_23_10 = {
	{t=1,starts={x=152.00,y=-57.00},sct={x=295.52,y=-143.36},dct={x=1096.00,y=667.00},ends={x=981.00,y=758.00},duration= 7, section=-1},
}
return fishpath_23_10
