--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_18_1 = {
	{t=1,starts={x=1120.00,y=744.00},sct={x=1152.37,y=578.15},dct={x=-205.34,y=164.31},ends={x=908.00,y=-56.00},duration= 7, section=-1},
}
return fishpath_18_1
