--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_14_8 = {
	{t=1,starts={x=1322.00,y=517.00},sct={x=1019.00,y=85.00},dct={x=-66.00,y=525.50},ends={x=407.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_14_8
