--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_15_3 = {
	{t=1,starts={x=169.00,y=750.00},sct={x=72.78,y=714.80},dct={x=-237.00,y=27.00},ends={x=342.00,y=20.00},duration= 7, section=-1},
	{t=1,starts={x=342.00,y=20.00},sct={x=560.32,y=20.43},dct={x=758.00,y=75.00},ends={x=1334.00,y=490.00},duration= 7, section=-1},
}
return fishpath_15_3
