--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_17_2 = {
	{t=1,starts={x=79.00,y=737.00},sct={x=62.84,y=733.96},dct={x=57.77,y=-85.48},ends={x=427.00,y=-16.00},duration= 7, section=-1},
	{t=1,starts={x=427.00,y=-16.00},sct={x=1132.89,y=217.00},dct={x=654.74,y=480.38},ends={x=1304.00,y=480.00},duration= 7, section=-1},
}
return fishpath_17_2
