--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_15_9 = {
	{t=1,starts={x=1307.00,y=90.00},sct={x=1098.90,y=577.11},dct={x=465.68,y=-662.31},ends={x=-33.00,y=656.00},duration= 7, section=-1},
}
return fishpath_15_9
