--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_16_3 = {
	{t=1,starts={x=1316.00,y=358.00},sct={x=997.00,y=717.00},dct={x=-679.90,y=742.34},ends={x=773.00,y=-52.00},duration= 7, section=-1},
}
return fishpath_16_3
