--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_15_2 = {
	{t=1,starts={x=-16.00,y=543.00},sct={x=536.00,y=614.00},dct={x=418.00,y=-120.00},ends={x=856.00,y=214.00},duration= 7, section=-1},
	{t=1,starts={x=856.00,y=214.00},sct={x=1386.53,y=654.35},dct={x=209.00,y=453.00},ends={x=-31.00,y=259.00},duration= 7, section=-1},
}
return fishpath_15_2
