--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_22_4 = {
	{t=1,starts={x=328.00,y=-54.00},sct={x=638.46,y=113.68},dct={x=331.69,y=626.73},ends={x=-27.00,y=433.00},duration= 7, section=-1},
}
return fishpath_22_4
