--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_12_7 = {
	{t=1,starts={x=-46.00,y=354.00},sct={x=967.48,y=109.41},dct={x=1489.47,y=-484.33},ends={x=1125.00,y=742.00},duration= 7, section=-1},
}
return fishpath_12_7
