--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_9_2 = {
	{t=1,starts={x=1310.00,y=537.00},sct={x=1341.29,y=452.19},dct={x=691.03,y=-80.60},ends={x=475.00,y=505.00},duration= 7, section=-1},
	{t=1,starts={x=475.00,y=505.00},sct={x=366.00,y=835.00},dct={x=-209.00,y=448.00},ends={x=188.00,y=130.00},duration= 7, section=-1},
	{t=1,starts={x=188.00,y=130.00},sct={x=576.00,y=-137.00},dct={x=1103.00,y=75.00},ends={x=1186.00,y=738.00},duration= 7, section=-1},
}
return fishpath_9_2
