--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_21_7 = {
	{t=1,starts={x=169.00,y=-69.00},sct={x=95.67,y=913.29},dct={x=1194.00,y=644.00},ends={x=1296.00,y=105.00},duration= 7, section=-1},
}
return fishpath_21_7
