--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_1_1 = {
	{t=1,starts={x=-68.00,y=328.00},sct={x=-4.16,y=298.32},dct={x=273.88,y=356.23},ends={x=412.00,y=544.00},duration= 7, section=-1},
	{t=1,starts={x=412.00,y=544.00},sct={x=630.17,y=760.36},dct={x=979.16,y=633.97},ends={x=834.67,y=490.67},duration= 7, section=-1},
	{t=1,starts={x=834.67,y=490.67},sct={x=638.18,y=230.42},dct={x=1025.04,y=177.51},ends={x=1089.33,y=262.67},duration= 7, section=-1},
	{t=1,starts={x=1089.33,y=262.67},sct={x=1240.20,y=501.11},dct={x=1507.79,y=172.91},ends={x=1434.67,y=57.33},duration= 7, section=-1},
}
return fishpath_1_1
