--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_7_8 = {
	{t=1,starts={x=1307.00,y=92.00},sct={x=1010.00,y=237.00},dct={x=1203.00,y=374.00},ends={x=935.00,y=564.00},duration= 7, section=-1},
	{t=1,starts={x=935.00,y=564.00},sct={x=673.59,y=709.63},dct={x=443.00,y=450.00},ends={x=509.00,y=159.00},duration= 7, section=-1},
	{t=1,starts={x=509.00,y=159.00},sct={x=585.00,y=-166.00},dct={x=-27.00,y=106.00},ends={x=-33.00,y=537.00},duration= 7, section=-1},
}
return fishpath_7_8
