--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_3_10 = {
	{t=1,starts={x=963.00,y=759.00},sct={x=1488.59,y=85.42},dct={x=-529.74,y=848.58},ends={x=351.00,y=-52.00},duration= 7, section=-1},
}
return fishpath_3_10
