--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_26_10 = {
	{t=1,starts={x=1334.00,y=24.00},sct={x=1321.94,y=-38.22},dct={x=141.28,y=227.39},ends={x=241.00,y=742.00},duration= 7, section=-1},
}
return fishpath_26_10
