--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_25_3 = {
	{t=1,starts={x=821.00,y=752.00},sct={x=742.30,y=737.93},dct={x=622.29,y=-113.95},ends={x=857.00,y=-72.00},duration= 7, section=-1},
}
return fishpath_25_3
