--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_24_8 = {
	{t=1,starts={x=150.00,y=835.00},sct={x=150.00,y=835.00},dct={x=1123.00,y=-80.00},ends={x=1123.00,y=-80.00},duration= 7, section=-1},
}
return fishpath_24_8
