--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_29_2 = {
	{t=1,starts={x=1317.00,y=667.00},sct={x=1345.77,y=636.06},dct={x=-3.87,y=30.54},ends={x=-48.00,y=78.00},duration= 7, section=-1},
}
return fishpath_29_2
