--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_26_9 = {
	{t=1,starts={x=1326.00,y=609.00},sct={x=1343.95,y=573.32},dct={x=156.60,y=79.20},ends={x=-31.00,y=452.00},duration= 7, section=-1},
}
return fishpath_26_9
