--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_3_1 = {
	{t=1,starts={x=183.00,y=756.00},sct={x=29.42,y=477.88},dct={x=939.00,y=887.00},ends={x=1044.00,y=567.00},duration= 7, section=-1},
	{t=1,starts={x=1044.00,y=567.00},sct={x=1183.00,y=-92.00},dct={x=1023.00,y=218.00},ends={x=105.00,y=-90.00},duration= 7, section=-1},
}
return fishpath_3_1
