--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_12_10 = {
	{t=1,starts={x=1214.00,y=-54.00},sct={x=250.00,y=300.00},dct={x=186.00,y=866.00},ends={x=-21.00,y=602.00},duration= 7, section=-1},
}
return fishpath_12_10
