--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_13_9 = {
	{t=1,starts={x=373.00,y=-58.00},sct={x=499.70,y=1077.71},dct={x=1280.92,y=131.39},ends={x=1151.00,y=737.00},duration= 7, section=-1},
}
return fishpath_13_9
