--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_3_5 = {
	{t=1,starts={x=-32.00,y=225.00},sct={x=136.54,y=-86.74},dct={x=1221.00,y=-97.00},ends={x=916.00,y=316.00},duration= 7, section=-1},
	{t=1,starts={x=916.00,y=316.00},sct={x=686.00,y=550.00},dct={x=812.00,y=691.00},ends={x=444.00,y=617.00},duration= 7, section=-1},
	{t=1,starts={x=444.00,y=617.00},sct={x=-19.00,y=528.00},dct={x=32.87,y=-45.65},ends={x=309.00,y=-71.00},duration= 7, section=-1},
}
return fishpath_3_5
