--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_3_9 = {
	{t=1,starts={x=1307.00,y=401.00},sct={x=475.00,y=798.00},dct={x=811.00,y=-192.00},ends={x=-28.00,y=426.00},duration= 7, section=-1},
}
return fishpath_3_9
