--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_24_6 = {
	{t=1,starts={x=1387.00,y=596.00},sct={x=1387.00,y=596.00},dct={x=-158.00,y=352.00},ends={x=-158.00,y=352.00},duration=25, section=-1},
}
return fishpath_24_6
