--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_18_9 = {
	{t=1,starts={x=149.33,y=944.00},sct={x=153.33,y=674.67},dct={x=1130.67,y=62.67},ends={x=1480.00,y=186.67},duration= 7, section=-1},
}
return fishpath_18_9
