--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_18_2 = {
	{t=1,starts={x=-20.00,y=551.00},sct={x=452.61,y=64.04},dct={x=144.20,y=729.18},ends={x=1315.00,y=658.00},duration= 7, section=-1},
}
return fishpath_18_2
