--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_23_5 = {
	{t=1,starts={x=1317.00,y=634.00},sct={x=1236.40,y=780.85},dct={x=181.26,y=386.26},ends={x=424.00,y=-56.00},duration= 7, section=-1},
}
return fishpath_23_5
