--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_24_8 = {
	{t=1,starts={x=150.00,y=835.00},sct={x=150.00,y=835.00},dct={x=1123.00,y=-80.00},ends={x=1123.00,y=-80.00},duration= 22, section=-1},
}
return fishpath_24_8
