--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_34_4 = {
	{t=1,starts={x=1194.67,y=894.67},sct={x=1173.33,y=149.33},dct={x=665.33,y=124.00},ends={x=-218.67,y=140.00},duration= 7, section=-1},
}
return fishpath_34_4
