--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_9_7 = {
	{t=1,starts={x=-21.00,y=360.00},sct={x=411.11,y=885.81},dct={x=163.00,y=145.00},ends={x=1294.00,y=-29.00},duration= 7, section=-1},
}
return fishpath_9_7
