--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_8_9 = {
	{t=1,starts={x=-28.00,y=144.00},sct={x=21.00,y=303.00},dct={x=252.01,y=415.92},ends={x=609.00,y=308.00},duration= 7, section=-1},
	{t=1,starts={x=609.00,y=308.00},sct={x=1471.58,y=52.43},dct={x=1283.00,y=682.00},ends={x=946.00,y=668.00},duration= 7, section=-1},
	{t=1,starts={x=946.00,y=668.00},sct={x=284.00,y=617.00},dct={x=335.00,y=79.00},ends={x=988.00,y=-58.00},duration= 7, section=-1},
}
return fishpath_8_9
