--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_33_2 = {
	{t=1,starts={x=326.67,y=945.33},sct={x=378.67,y=782.67},dct={x=24.88,y=30.73},ends={x=57.33,y=-204.00},duration= 7, section=-1},
}
return fishpath_33_2
