--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_9_3 = {
	{t=1,starts={x=1299.00,y=634.00},sct={x=374.27,y=749.32},dct={x=216.53,y=138.14},ends={x=787.00,y=67.00},duration= 7, section=-1},
	{t=1,starts={x=787.00,y=67.00},sct={x=1488.00,y=-26.00},dct={x=1098.00,y=490.00},ends={x=250.00,y=480.00},duration= 7, section=-1},
	{t=1,starts={x=250.00,y=480.00},sct={x=-236.00,y=465.00},dct={x=619.00,y=655.00},ends={x=770.00,y=740.00},duration= 7, section=-1},
}
return fishpath_9_3
