--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_11_4 = {
	{t=1,starts={x=134.00,y=-82.00},sct={x=44.00,y=-19.00},dct={x=268.00,y=189.00},ends={x=622.00,y=438.00},duration= 7, section=-1},
	{t=1,starts={x=622.00,y=438.00},sct={x=965.29,y=637.56},dct={x=1003.00,y=271.00},ends={x=1321.00,y=130.00},duration= 7, section=-1},
}
return fishpath_11_4
