--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_30_1 = {
	{t=1,starts={x=152.00,y=806.00},sct={x=152.00,y=806.00},dct={x=1434.00,y=-100.00},ends={x=1434.00,y=-100.00},duration= 7, section=-1},
}
return fishpath_30_1
