--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_18_4 = {
	{t=1,starts={x=274.00,y=-60.00},sct={x=80.33,y=-13.21},dct={x=962.53,y=736.96},ends={x=1310.00,y=653.00},duration= 7, section=-1},
}
return fishpath_18_4
