--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_16_10 = {
	{t=1,starts={x=271.00,y=-56.00},sct={x=183.00,y=83.00},dct={x=-125.38,y=356.50},ends={x=204.00,y=422.00},duration= 7, section=-1},
	{t=1,starts={x=204.00,y=422.00},sct={x=913.47,y=539.39},dct={x=1321.91,y=-14.37},ends={x=1306.00,y=-17.00},duration= 7, section=-1},
}
return fishpath_16_10
