--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_6_7 = {
	{t=1,starts={x=268.00,y=-73.00},sct={x=23.00,y=186.00},dct={x=56.00,y=540.00},ends={x=368.00,y=554.00},duration= 7, section=-1},
	{t=1,starts={x=368.00,y=554.00},sct={x=1123.00,y=581.00},dct={x=1089.00,y=222.00},ends={x=942.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_6_7
