--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_32_6 = {
	{t=1,starts={x=942.67,y=920.00},sct={x=942.67,y=920.00},dct={x=936.00,y=324.00},ends={x=936.00,y=324.00},duration= 7, section=-1},
	{t=1,starts={x=936.00,y=324.00},sct={x=944.00,y=80.00},dct={x=664.00,y=161.33},ends={x=400.00,y=465.33},duration= 7, section=-1},
	{t=1,starts={x=400.00,y=465.33},sct={x=273.33,y=628.00},dct={x=-185.33,y=456.00},ends={x=232.00,y=-126.67},duration= 7, section=-1},
}
return fishpath_32_6
