--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_18_3 = {
	{t=1,starts={x=1306.00,y=147.00},sct={x=912.00,y=271.00},dct={x=-51.77,y=562.88},ends={x=298.00,y=-62.00},duration= 7, section=-1},
}
return fishpath_18_3
