--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_22_10 = {
	{t=1,starts={x=170.00,y=752.00},sct={x=457.64,y=762.91},dct={x=1102.00,y=26.00},ends={x=973.00,y=-61.00},duration= 7, section=-1},
}
return fishpath_22_10
