--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_8_7 = {
	{t=1,starts={x=1294.00,y=563.00},sct={x=942.00,y=652.00},dct={x=123.00,y=154.00},ends={x=303.00,y=-50.00},duration= 7, section=-1},
}
return fishpath_8_7
