--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_3_3 = {
	{t=1,starts={x=1298.00,y=484.00},sct={x=1147.42,y=408.08},dct={x=1277.57,y=-192.64},ends={x=915.00,y=62.00},duration= 7, section=-1},
	{t=1,starts={x=915.00,y=62.00},sct={x=562.00,y=278.00},dct={x=1227.00,y=677.00},ends={x=766.00,y=640.00},duration= 7, section=-1},
	{t=1,starts={x=766.00,y=640.00},sct={x=293.00,y=570.00},dct={x=127.00,y=454.00},ends={x=204.00,y=-56.00},duration= 7, section=-1},
}
return fishpath_3_3
