--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_24_1 = {
	{t=1,starts={x=-141.00,y=405.00},sct={x=-141.00,y=405.00},dct={x=1372.00,y=546.00},ends={x=1372.00,y=546.00},duration= 18, section=-1},
}
return fishpath_24_1
