--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_11_8 = {
	{t=1,starts={x=-42.00,y=323.00},sct={x=995.55,y=928.78},dct={x=1812.34,y=678.59},ends={x=573.00,y=-45.00},duration= 7, section=-1},
}
return fishpath_11_8
