--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_34_5 = {
	{t=1,starts={x=-218.67,y=804.00},sct={x=370.67,y=592.00},dct={x=1144.00,y=324.00},ends={x=749.33,y=-142.67},duration= 7, section=-1},
}
return fishpath_34_5
