--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_23_2 = {
	{t=1,starts={x=-44.00,y=305.00},sct={x=70.75,y=539.57},dct={x=1167.57,y=528.55},ends={x=1320.00,y=271.00},duration= 7, section=-1},
}
return fishpath_23_2
