--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_22_1 = {
	{t=1,starts={x=-47.00,y=131.00},sct={x=269.41,y=548.15},dct={x=648.98,y=390.47},ends={x=1337.00,y=496.00},duration= 7, section=-1},
}
return fishpath_22_1
