--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_34_1 = {
	{t=1,starts={x=46.67,y=-206.67},sct={x=46.67,y=-206.67},dct={x=660.00,y=912.00},ends={x=660.00,y=912.00},duration= 7, section=-1},
}
return fishpath_34_1
