--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_15_10 = {
	{t=1,starts={x=1043.00,y=737.00},sct={x=476.35,y=678.18},dct={x=345.51,y=-16.46},ends={x=822.00,y=33.00},duration= 7, section=-1},
	{t=1,starts={x=822.00,y=33.00},sct={x=1344.00,y=104.00},dct={x=805.00,y=352.00},ends={x=1302.00,y=467.00},duration= 7, section=-1},
}
return fishpath_15_10
