--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_15_7 = {
	{t=1,starts={x=-18.00,y=557.00},sct={x=822.00,y=-147.00},dct={x=1002.37,y=702.31},ends={x=1296.00,y=235.00},duration= 7, section=-1},
}
return fishpath_15_7
