--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_7_6 = {
	{t=1,starts={x=-30.00,y=-2.00},sct={x=-53.07,y=196.94},dct={x=232.00,y=225.00},ends={x=664.00,y=560.00},duration= 7, section=-1},
	{t=1,starts={x=664.00,y=560.00},sct={x=845.92,y=698.05},dct={x=1238.09,y=494.98},ends={x=1074.00,y=370.00},duration= 7, section=-1},
	{t=1,starts={x=1074.00,y=370.00},sct={x=694.00,y=56.00},dct={x=871.00,y=23.00},ends={x=420.00,y=-67.00},duration= 7, section=-1},
}
return fishpath_7_6
