--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_19_8 = {
	{t=1,starts={x=1318.00,y=477.00},sct={x=628.85,y=525.97},dct={x=546.81,y=767.08},ends={x=-21.00,y=292.00},duration= 7, section=-1},
}
return fishpath_19_8
