--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_25_4 = {
	{t=1,starts={x=1322.00,y=635.00},sct={x=1203.00,y=664.00},dct={x=481.33,y=109.03},ends={x=625.00,y=-75.00},duration= 7, section=-1},
}
return fishpath_25_4
