--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_3_6 = {
	{t=1,starts={x=359.00,y=-48.00},sct={x=364.25,y=-71.74},dct={x=972.00,y=164.00},ends={x=961.00,y=517.00},duration= 7, section=-1},
	{t=1,starts={x=961.00,y=517.00},sct={x=950.00,y=716.00},dct={x=418.00,y=778.00},ends={x=288.00,y=601.00},duration= 7, section=-1},
	{t=1,starts={x=288.00,y=601.00},sct={x=44.00,y=-24.00},dct={x=504.00,y=402.00},ends={x=1098.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_3_6
