--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_24_2 = {
	{t=1,starts={x=-139.00,y=121.00},sct={x=-139.00,y=121.00},dct={x=1360.00,y=383.00},ends={x=1360.00,y=383.00},duration= 7, section=-1},
}
return fishpath_24_2
