--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp May-25-16 17:29:18
local fishpath_10_3 = {
	{t=1,starts={x=947.00,y=733.00},sct={x=1109.50,y=496.08},dct={x=-257.17,y=-341.21},ends={x=168.00,y=258.00},duration= 5, section=-1},
	{t=1,starts={x=168.00,y=258.00},sct={x=518.66,y=790.06},dct={x=813.02,y=41.58},ends={x=129.00,y=-71.00},duration= 5, section=-1},
}
return fishpath_10_3
