--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_14_10 = {
	{t=1,starts={x=1293.00,y=647.00},sct={x=985.30,y=635.75},dct={x=529.70,y=-341.66},ends={x=329.00,y=107.00},duration= 7, section=-1},
	{t=1,starts={x=329.00,y=107.00},sct={x=22.36,y=760.68},dct={x=1126.00,y=488.00},ends={x=1319.00,y=190.00},duration= 7, section=-1},
}
return fishpath_14_10
