--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_32_2 = {
	{t=1,starts={x=-240.00,y=120.00},sct={x=-240.00,y=120.00},dct={x=408.00,y=270.00},ends={x=560.00,y=-195.00},duration= 7, section=-1},
}
return fishpath_32_2
