--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_20_5 = {
	{t=1,starts={x=1306.00,y=559.00},sct={x=-153.56,y=683.41},dct={x=166.58,y=344.73},ends={x=186.00,y=-56.00},duration= 7, section=-1},
}
return fishpath_20_5
