--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_9_4 = {
	{t=1,starts={x=1300.00,y=642.00},sct={x=219.00,y=655.00},dct={x=851.00,y=146.00},ends={x=529.00,y=63.00},duration= 7, section=-1},
	{t=1,starts={x=529.00,y=63.00},sct={x=238.45,y=-24.08},dct={x=-181.00,y=347.00},ends={x=255.00,y=503.00},duration= 7, section=-1},
	{t=1,starts={x=255.00,y=503.00},sct={x=748.48,y=647.64},dct={x=1288.13,y=-38.72},ends={x=1179.00,y=-70.00},duration= 7, section=-1},
}
return fishpath_9_4
