--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_13_4 = {
	{t=1,starts={x=-37.00,y=464.00},sct={x=70.00,y=641.00},dct={x=554.00,y=792.00},ends={x=923.00,y=578.00},duration= 7, section=-1},
	{t=1,starts={x=923.00,y=578.00},sct={x=1474.94,y=189.39},dct={x=950.00,y=226.00},ends={x=228.00,y=-46.00},duration= 7, section=-1},
}
return fishpath_13_4
