--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_25_5 = {
	{t=1,starts={x=-59.00,y=89.00},sct={x=-49.93,y=203.36},dct={x=1321.99,y=261.60},ends={x=1330.00,y=104.00},duration= 7, section=-1},
}
return fishpath_25_5
