--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_19_1 = {
	{t=1,starts={x=1306.00,y=465.00},sct={x=1106.00,y=-27.00},dct={x=376.55,y=123.34},ends={x=-63.00,y=492.00},duration= 7, section=-1},
}
return fishpath_19_1
