--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_8_1 = {
	{t=1,starts={x=296.00,y=-50.00},sct={x=114.00,y=205.00},dct={x=221.44,y=798.29},ends={x=561.00,y=630.00},duration= 7, section=-1},
	{t=1,starts={x=561.00,y=630.00},sct={x=905.00,y=423.00},dct={x=876.00,y=198.00},ends={x=1306.00,y=433.00},duration= 7, section=-1},
}
return fishpath_8_1
