--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_3_7 = {
	{t=1,starts={x=-24.00,y=-29.00},sct={x=-27.09,y=242.93},dct={x=485.48,y=652.62},ends={x=492.00,y=79.00},duration= 7, section=-1},
	{t=1,starts={x=492.00,y=79.00},sct={x=499.37,y=-117.48},dct={x=923.77,y=-28.64},ends={x=918.00,y=125.00},duration= 7, section=-1},
	{t=1,starts={x=918.00,y=125.00},sct={x=890.00,y=584.00},dct={x=1306.40,y=346.81},ends={x=1305.00,y=228.00},duration= 7, section=-1},
}
return fishpath_3_7
