--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_11_9 = {
	{t=1,starts={x=-51.00,y=189.00},sct={x=146.94,y=787.54},dct={x=344.00,y=779.00},ends={x=1208.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_11_9
