--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_10_11 = {
	{t=1,starts={x=-30.00,y=360.00},sct={x=-30.00,y=360.00},dct={x=1940.00,y=360.00},ends={x=1940.00,y=360.00},duration= 7, section=-1},
}
return fishpath_10_11
