--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_24_10 = {
	{t=1,starts={x=1412.00,y=103.00},sct={x=1412.00,y=103.00},dct={x=-149.00,y=681.00},ends={x=-149.00,y=681.00},duration= 7, section=-1},
}
return fishpath_24_10
