--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_20_3 = {
	{t=1,starts={x=192.00,y=760.00},sct={x=151.84,y=-274.89},dct={x=730.17,y=633.98},ends={x=1295.00,y=647.00},duration= 7, section=-1},
}
return fishpath_20_3
