--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_7_2 = {
	{t=1,starts={x=1301.00,y=686.00},sct={x=1275.00,y=525.00},dct={x=1232.00,y=387.00},ends={x=503.00,y=418.00},duration= 7, section=-1},
	{t=1,starts={x=503.00,y=418.00},sct={x=156.00,y=445.00},dct={x=-26.00,y=68.00},ends={x=43.00,y=-54.00},duration= 7, section=-1},
}
return fishpath_7_2
