--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_16_9 = {
	{t=1,starts={x=-49.00,y=189.00},sct={x=372.44,y=465.32},dct={x=1098.53,y=456.63},ends={x=428.00,y=17.00},duration= 7, section=-1},
	{t=1,starts={x=428.00,y=17.00},sct={x=68.00,y=-192.00},dct={x=20.54,y=633.75},ends={x=358.00,y=627.00},duration= 7, section=-1},
	{t=1,starts={x=358.00,y=627.00},sct={x=839.46,y=610.58},dct={x=581.67,y=258.55},ends={x=1313.00,y=551.00},duration= 7, section=-1},
}
return fishpath_16_9
