--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_8_3 = {
	{t=1,starts={x=139.00,y=-53.00},sct={x=23.43,y=67.92},dct={x=342.71,y=442.29},ends={x=494.00,y=284.00},duration= 7, section=-1},
	{t=1,starts={x=494.00,y=284.00},sct={x=767.00,y=-1.00},dct={x=1038.00,y=557.00},ends={x=980.00,y=730.00},duration= 7, section=-1},
}
return fishpath_8_3
