--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_12_3 = {
	{t=1,starts={x=262.00,y=-94.00},sct={x=830.68,y=249.01},dct={x=1875.13,y=620.26},ends={x=689.00,y=600.00},duration= 7, section=-1},
	{t=1,starts={x=689.00,y=600.00},sct={x=-291.27,y=586.23},dct={x=901.79,y=-188.90},ends={x=1359.00,y=76.00},duration= 7, section=-1},
}
return fishpath_12_3
