--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_3_8 = {
	{t=1,starts={x=1324.00,y=51.00},sct={x=1113.00,y=135.00},dct={x=1189.00,y=445.00},ends={x=1032.00,y=556.00},duration= 7, section=-1},
	{t=1,starts={x=1032.00,y=556.00},sct={x=846.00,y=668.00},dct={x=434.77,y=374.66},ends={x=390.00,y=542.00},duration= 7, section=-1},
	{t=1,starts={x=390.00,y=542.00},sct={x=282.00,y=767.00},dct={x=115.00,y=576.00},ends={x=122.00,y=765.00},duration= 7, section=-1},
}
return fishpath_3_8
