--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_22_5 = {
	{t=1,starts={x=1180.00,y=-63.00},sct={x=1145.78,y=89.08},dct={x=555.64,y=771.16},ends={x=-23.00,y=637.00},duration= 7, section=-1},
}
return fishpath_22_5
