--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_2_1 = {
	{t=1,starts={x=777.00,y=760.00},sct={x=1070.00,y=293.00},dct={x=425.00,y=611.00},ends={x=302.00,y=476.00},duration= 7, section=-1},
	{t=1,starts={x=302.00,y=476.00},sct={x=105.00,y=209.00},dct={x=335.00,y=285.00},ends={x=654.00,y=-63.00},duration= 7, section=-1},
}
return fishpath_2_1
