--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_17_7 = {
	{t=1,starts={x=1306.00,y=563.00},sct={x=994.00,y=-100.00},dct={x=290.00,y=-13.00},ends={x=-49.00,y=113.00},duration= 7, section=-1},
}
return fishpath_17_7
