--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_12_4 = {
	{t=1,starts={x=1312.00,y=570.00},sct={x=495.16,y=1038.00},dct={x=1537.00,y=-394.45},ends={x=-44.00,y=123.00},duration= 7, section=-1},
}
return fishpath_12_4
