--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_18_6 = {
	{t=1,starts={x=214.67,y=-166.67},sct={x=124.00,y=174.67},dct={x=420.00,y=318.67},ends={x=673.33,y=366.67},duration= 7, section=-1},
	{t=1,starts={x=673.33,y=366.67},sct={x=1165.33,y=470.67},dct={x=1124.00,y=716.00},ends={x=1020.00,y=936.00},duration= 7, section=-1},
}
return fishpath_18_6
