--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_24_9 = {
	{t=1,starts={x=-151.00,y=575.00},sct={x=-151.00,y=575.00},dct={x=1438.00,y=538.00},ends={x=1438.00,y=538.00},duration= 21, section=-1},
}
return fishpath_24_9
