--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_14_6 = {
	{t=1,starts={x=1293.00,y=502.00},sct={x=964.29,y=968.17},dct={x=-104.72,y=214.68},ends={x=726.00,y=52.00},duration= 7, section=-1},
	{t=1,starts={x=726.00,y=52.00},sct={x=1442.00,y=-73.00},dct={x=167.90,y=1101.15},ends={x=107.00,y=-46.00},duration= 7, section=-1},
}
return fishpath_14_6
