--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_25_1 = {
	{t=1,starts={x=932.00,y=-78.00},sct={x=994.98,y=-45.93},dct={x=232.29,y=684.46},ends={x=-20.00,y=557.00},duration= 7, section=-1},
}
return fishpath_25_1
