--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_20_4 = {
	{t=1,starts={x=-21.00,y=408.00},sct={x=784.71,y=41.84},dct={x=651.34,y=200.18},ends={x=1173.00,y=739.00},duration= 7, section=-1},
}
return fishpath_20_4
