--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_3_4 = {
	{t=1,starts={x=1305.00,y=114.00},sct={x=1044.00,y=178.00},dct={x=1128.00,y=644.00},ends={x=772.00,y=363.00},duration= 7, section=-1},
	{t=1,starts={x=772.00,y=363.00},sct={x=74.00,y=-192.00},dct={x=51.52,y=604.27},ends={x=226.00,y=752.00},duration= 7, section=-1},
}
return fishpath_3_4
