--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_15_5 = {
	{t=1,starts={x=431.00,y=-64.00},sct={x=596.43,y=336.51},dct={x=1162.55,y=356.18},ends={x=650.00,y=588.00},duration= 7, section=-1},
	{t=1,starts={x=650.00,y=588.00},sct={x=372.11,y=685.31},dct={x=482.08,y=9.35},ends={x=662.00,y=-53.00},duration= 7, section=-1},
}
return fishpath_15_5
