--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_2_11 = {
	{t=1,starts={x=640.00,y=950.00},sct={x=640.00,y=950.00},dct={x=640.00,y=-208.00},ends={x=640.00,y=-208.00},duration= 7, section=-1},
}
return fishpath_2_11
