--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_20_2 = {
	{t=1,starts={x=800.00,y=-59.00},sct={x=221.12,y=175.87},dct={x=995.05,y=487.67},ends={x=1114.00,y=734.00},duration= 7, section=-1},
}
return fishpath_20_2
