--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_24_6 = {
	{t=1,starts={x=1387.00,y=596.00},sct={x=1387.00,y=596.00},dct={x=-158.00,y=352.00},ends={x=-158.00,y=352.00},duration= 7, section=-1},
}
return fishpath_24_6
