--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_16_8 = {
	{t=1,starts={x=1322.00,y=259.00},sct={x=801.00,y=837.00},dct={x=-203.42,y=499.21},ends={x=1128.00,y=-53.00},duration= 7, section=-1},
}
return fishpath_16_8
