--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_21_8 = {
	{t=1,starts={x=943.00,y=-57.00},sct={x=1355.00,y=230.00},dct={x=1007.65,y=821.04},ends={x=-29.00,y=556.00},duration= 7, section=-1},
}
return fishpath_21_8
