--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_17_6 = {
	{t=1,starts={x=-23.00,y=84.00},sct={x=447.00,y=-70.00},dct={x=441.00,y=411.00},ends={x=1227.00,y=740.00},duration= 7, section=-1},
}
return fishpath_17_6
