--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_16_5 = {
	{t=2,starts={x=1310.00,y=532.00},ends={x=523.00,y=-45.00},duration= 7, section=-1},
	{t=2,starts={x=1310.00,y=532.00},ends={x=523.00,y=-45.00},duration= 7, section=-1},
}
return fishpath_16_5
