--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_5_6 = {
	{t=1,starts={x=1304.00,y=646.00},sct={x=235.58,y=827.65},dct={x=523.00,y=207.00},ends={x=137.00,y=-60.00},duration= 7, section=-1},
}
return fishpath_5_6
