--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_29_1 = {
	{t=1,starts={x=-48.00,y=694.00},sct={x=-84.61,y=627.11},dct={x=1223.63,y=-98.81},ends={x=1310.00,y=59.00},duration= 7, section=-1},
}
return fishpath_29_1
