--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_6_2 = {
	{t=1,starts={x=1307.00,y=612.00},sct={x=1214.00,y=339.00},dct={x=866.00,y=106.00},ends={x=566.00,y=498.00},duration= 7, section=-1},
	{t=1,starts={x=566.00,y=498.00},sct={x=341.00,y=771.00},dct={x=-179.00,y=274.00},ends={x=620.00,y=-55.00},duration= 7, section=-1},
}
return fishpath_6_2
