--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_33_3 = {
	{t=1,starts={x=570.67,y=930.67},sct={x=529.73,y=705.61},dct={x=1077.29,y=98.91},ends={x=1501.33,y=186.67},duration= 7, section=-1},
}
return fishpath_33_3
