--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_26_1 = {
	{t=1,starts={x=-39.00,y=186.00},sct={x=-37.41,y=181.85},dct={x=1261.31,y=497.55},ends={x=1161.00,y=759.00},duration= 7, section=-1},
}
return fishpath_26_1
