--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_21_5 = {
	{t=1,starts={x=188.00,y=-63.00},sct={x=35.91,y=265.36},dct={x=902.00,y=374.00},ends={x=1114.00,y=734.00},duration= 7, section=-1},
}
return fishpath_21_5
