--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_12_2 = {
	{t=1,starts={x=1142.00,y=739.00},sct={x=1167.85,y=-117.48},dct={x=-418.73,y=752.25},ends={x=242.00,y=-52.00},duration= 7, section=-1},
}
return fishpath_12_2
