--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_34_2 = {
	{t=1,starts={x=776.00,y=916.00},sct={x=617.33,y=714.67},dct={x=204.76,y=471.51},ends={x=474.67,y=274.67},duration= 7, section=-1},
	{t=1,starts={x=474.67,y=274.67},sct={x=808.00,y=49.33},dct={x=1157.33,y=44.00},ends={x=1277.33,y=-140.00},duration= 7, section=-1},
}
return fishpath_34_2
