--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_4_4 = {
	{t=1,starts={x=-25.00,y=-6.00},sct={x=886.00,y=65.02},dct={x=341.00,y=322.00},ends={x=892.00,y=742.00},duration= 7, section=-1},
}
return fishpath_4_4
