--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_33_5 = {
	{t=1,starts={x=-100.00,y=890.67},sct={x=-37.33,y=320.00},dct={x=1077.33,y=248.00},ends={x=1224.00,y=-134.67},duration= 7, section=-1},
}
return fishpath_33_5
