--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_24_3 = {
	{t=1,starts={x=141.00,y=-111.00},sct={x=141.00,y=-111.00},dct={x=600.00,y=817.00},ends={x=600.00,y=817.00},duration= 7, section=-1},
}
return fishpath_24_3
