--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_19_9 = {
	{t=1,starts={x=1305.00,y=5.00},sct={x=1156.00,y=632.00},dct={x=128.61,y=428.04},ends={x=256.00,y=-68.00},duration= 7, section=-1},
}
return fishpath_19_9
