--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_15_6 = {
	{t=1,starts={x=307.00,y=-88.00},sct={x=256.24,y=-114.93},dct={x=-33.29,y=324.96},ends={x=374.00,y=541.00},duration= 7, section=-1},
	{t=1,starts={x=374.00,y=541.00},sct={x=843.10,y=713.27},dct={x=721.00,y=604.00},ends={x=1319.00,y=497.00},duration= 7, section=-1},
}
return fishpath_15_6
