--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_2_10 = {
	{t=1,starts={x=659.00,y=-71.00},sct={x=666.00,y=222.00},dct={x=156.00,y=-142.00},ends={x=151.00,y=272.00},duration= 7, section=-1},
	{t=1,starts={x=151.00,y=272.00},sct={x=150.00,y=672.00},dct={x=850.00,y=698.00},ends={x=1308.00,y=397.00},duration= 7, section=-1},
}
return fishpath_2_10
