--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_19_10 = {
	{t=1,starts={x=164.00,y=739.00},sct={x=85.97,y=-84.09},dct={x=1064.16,y=-249.72},ends={x=1157.00,y=743.00},duration= 7, section=-1},
}
return fishpath_19_10
