--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_17_9 = {
	{t=1,starts={x=-33.00,y=94.00},sct={x=-74.37,y=296.63},dct={x=1301.00,y=208.00},ends={x=1321.00,y=87.00},duration= 7, section=-1},
}
return fishpath_17_9
