--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_21_1 = {
	{t=1,starts={x=-33.00,y=132.00},sct={x=226.24,y=623.90},dct={x=774.00,y=170.00},ends={x=1315.00,y=126.00},duration= 7, section=-1},
}
return fishpath_21_1
