--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_13_10 = {
	{t=1,starts={x=103.00,y=-73.00},sct={x=-94.72,y=556.52},dct={x=393.75,y=1186.75},ends={x=1287.00,y=35.00},duration= 7, section=-1},
}
return fishpath_13_10
