--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_34_3 = {
	{t=1,starts={x=-242.67,y=404.00},sct={x=-110.67,y=552.00},dct={x=713.33,y=829.33},ends={x=894.67,y=522.67},duration= 7, section=-1},
	{t=1,starts={x=894.67,y=522.67},sct={x=1057.33,y=237.33},dct={x=670.67,y=54.67},ends={x=1144.00,y=-132.00},duration= 7, section=-1},
}
return fishpath_34_3
