--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_32_4 = {
	{t=1,starts={x=1660.00,y=930.00},sct={x=1660.00,y=930.00},dct={x=-342.00,y=-188.00},ends={x=-342.00,y=-188.00},duration= 7, section=-1},
}
return fishpath_32_4
