--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_13_3 = {
	{t=1,starts={x=413.00,y=753.00},sct={x=-495.24,y=204.84},dct={x=2049.88,y=646.19},ends={x=598.00,y=-49.00},duration= 7, section=-1},
}
return fishpath_13_3
