--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_6_5 = {
	{t=1,starts={x=-23.00,y=292.00},sct={x=116.00,y=551.00},dct={x=381.00,y=642.00},ends={x=693.00,y=621.00},duration= 7, section=-1},
	{t=1,starts={x=693.00,y=621.00},sct={x=1031.00,y=579.00},dct={x=790.00,y=443.00},ends={x=1297.00,y=285.00},duration= 7, section=-1},
}
return fishpath_6_5
