--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 15:45:47
local fishpath_14_7 = {
	{t=1,starts={x=1152.00,y=-60.00},sct={x=1003.00,y=433.00},dct={x=-165.92,y=108.86},ends={x=469.00,y=729.00},duration= 7, section=-1},
}
return fishpath_14_7
