--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_28_2 = {
	{t=1,starts={x=1149.00,y=750.00},sct={x=1290.84,y=657.20},dct={x=181.83,y=-129.48},ends={x=-39.00,y=15.00},duration= 7, section=-1},
}
return fishpath_28_2
