--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 16:30:27
local fishpath_14_5 = {
	{t=1,starts={x=1120.00,y=-46.00},sct={x=1015.00,y=82.00},dct={x=1269.00,y=113.00},ends={x=1184.00,y=290.00},duration= 7, section=-1},
	{t=1,starts={x=1184.00,y=290.00},sct={x=1067.00,y=488.00},dct={x=-5.97,y=540.59},ends={x=559.00,y=736.00},duration= 7, section=-1},
}
return fishpath_14_5
