--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_22_6 = {
	{t=1,starts={x=1315.00,y=27.00},sct={x=1288.00,y=263.00},dct={x=99.27,y=747.93},ends={x=-41.00,y=613.00},duration= 7, section=-1},
}
return fishpath_22_6
