--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Jun-12-16 09:59:14
local fishpath_23_1 = {
	{t=1,starts={x=157.00,y=-61.00},sct={x=264.46,y=-63.23},dct={x=1320.75,y=494.71},ends={x=1061.00,y=751.00},duration= 7, section=-1},
}
return fishpath_23_1
