--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_16_6 = {
	{t=1,starts={x=1323.00,y=507.00},sct={x=794.00,y=252.00},dct={x=952.12,y=576.88},ends={x=488.00,y=409.00},duration= 7, section=-1},
	{t=1,starts={x=488.00,y=409.00},sct={x=-300.77,y=159.26},dct={x=935.00,y=134.00},ends={x=1059.00,y=-57.00},duration= 7, section=-1},
}
return fishpath_16_6
