--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!
--ppp Sep-20-16 14:41:23
local fishpath_12_1 = {
	{t=1,starts={x=-18.00,y=697.00},sct={x=279.00,y=86.00},dct={x=-320.00,y=44.00},ends={x=1253.00,y=-50.00},duration= 7, section=-1},
}
return fishpath_12_1
