#!/bin/python

import os
import os.path
from xml.dom.minidom import parse
import xml.dom.minidom
import re
import datetime

numPairRe = re.compile(r'(\d\d)')

def getPoints(simple):
	rst = re.split(r"[\t \n]+", simple)
	nums = []
	for a in rst:
		if re.search(r',', a):
			num = re.split(r',', a)
			if len(num) == 2:
				num[0] = float(num[0])
				num[1] = float(num[1])
			nums.append(num)

	return nums		

rootdir = os.path.join(os.getcwd() , "singlePath")
outdir = os.path.join(os.getcwd(), "pathconfig")

def formatPair(name, aPair):
	return "%s={x=%.2f,y=%.2f}" % (name, aPair[0], 720 - aPair[1])

def parseFile(aPath, outPath, name):
	DOMTree = xml.dom.minidom.parse(open(aPath))
	lPath = DOMTree.getElementsByTagName("path")[0].getAttribute("d")
	lPoints = getPoints(lPath)
	curTime = datetime.datetime.now().strftime('%b-%d-%y %H:%M:%S');
	file = open(outPath, 'wb')
	file.write("--!!!AUTOGENERATED, MODIFY AS YOU WISH!!!\n")
	file.write("--ppp " + curTime + "\n")
	file.write("local " + name + " = {\n")

	startIdx = 0
	while startIdx < len(lPoints) - 1:
		file.write("\t{t=1,")
		file.write(formatPair('starts', lPoints[startIdx]))
		file.write(",")
		file.write(formatPair('sct', lPoints[startIdx + 1]))
		file.write(",")
		file.write(formatPair('dct', lPoints[startIdx + 2]))
		file.write(",")
		file.write(formatPair('ends', lPoints[startIdx + 3]))
		file.write(",")
		file.write("duration= 7, section=-1},\n")
		startIdx = startIdx + 3

	file.write("}\nreturn " + name + "\n")
	file.close()

for parent, dirnames, filenames in os.walk(rootdir):
	for filename in filenames:
		print "handling file ", os.path.join(parent, filename)
		name = re.split(r'\.', filename)[0]
		parseFile(os.path.join(parent, filename), os.path.join(outdir, name + ".lua"), name)

os.system("rmdir /s /q genPoint")
os.system("mkdir genPoint")
os.system("lua.exe main.lua")
os.system("pause")
